Repository ESCOMP/CTSM, pull requests merged in 2018-04, with the labels that each got.

#241 add support for 64bit_data, fix fillvalues
  src/biogeophys/TemperatureType.F90
  src/main/ncdio_pio.F90.in
Labels: tag: simple bfb, type: enhance - software

#319 updates to FATES test category
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdDef/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdDef/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesShortList/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesShortList/shell_commands
Labels: type: enhance - software

#333 List of important bug fixes
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_clm4_0.xml
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/cplhist/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/cplhist/shell_commands
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/findHistFields.pl
  src/main/histFileMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeCNMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
Labels: priority: high, type: bug - other

#305 Add tests for aux_cime_baselines edison tests for fates
  cime_config/testdefs/testlist_clm.xml
Labels: priority: high, type: enhance - software

#349 Update manage-externals to manic-v1.1.3
  manage_externals/README.md
  manage_externals/manic/checkout.py
  manage_externals/manic/externals_description.py
  manage_externals/manic/repository.py
  manage_externals/manic/repository_git.py
  manage_externals/manic/repository_svn.py
  manage_externals/manic/sourcetree.py
  manage_externals/manic/utils.py
  manage_externals/test/Makefile
  manage_externals/test/repos/simple-ext.git/objects/09/0e1034746b2c865f7b0280813dbf4061a700e8
  manage_externals/test/repos/simple-ext.git/objects/31/dbcd6de441e671a467ef317146539b7ffabb11
  manage_externals/test/repos/simple-ext.git/objects/60/b1cc1a38d63a4bcaa1e767262bbe23dbf9f5f5
  manage_externals/test/repos/simple-ext.git/objects/63/a99393d1baff97ccef967af30380659867b139
  manage_externals/test/repos/simple-ext.git/objects/95/3256da5612fcd9263590a353bc18c6f224e74f
  manage_externals/test/repos/simple-ext.git/objects/df/312890f93ba4d2c694208599b665c4a08afeff
  manage_externals/test/repos/simple-ext.git/refs/heads/feature3
  manage_externals/test/test_sys_checkout.py
  manage_externals/test/test_sys_repository_git.py
  manage_externals/test/test_unit_externals_description.py
  manage_externals/test/test_unit_repository.py
  manage_externals/test/test_unit_repository_git.py
  manage_externals/test/test_unit_repository_svn.py
Labels: priority: high, type: enhance - software

#344 added changes to remove denit and nit fluxes from N available to FUN
  src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90
Labels: priority: high, type: bug - impacts science
