Repository ESCOMP/CTSM, pull requests merged in 2018-02, with the labels that each got.

#261 Reorder links
  README.rst
Labels: type: docs - non-code

#295 Bring in a working PTCLMmkdata version
  .gitignore
  Externals_CLM.cfg
Labels: priority: high, severity: critical, type: bug - impacts science

#296 Make LND_TUNING_MODE correct and consistent when coupled with CAM
  bld/unit_testers/xFail/expectedFail.pm
  cime_config/config_component.xml
Labels: priority: high, severity: critical, type: bug - impacts science

#297 Some work on the README files
  README
  doc/ChangeLog
  doc/CodeReference/Filepath
  doc/CodeReference/Makefile
  doc/KnownBugs
  doc/KnownLimitations
  doc/Quickstart.GUIDE
  doc/README
  doc/clm4_5_ChangeLog
  doc/index.shtml
Labels: priority: high, type: code cleanup/docs
