Repository ESCOMP/CTSM, pull requests merged in 2018-06, with the labels that each got.

#390 Fates history dimensions: height, age*pft, size*age*pft
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type:FATES Next API

#375 variable soil depth compatibility with FATES
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  src/utils/clmfates_interfaceMod.F90
Labels: type:FATES Next API

#400 Update CanopyStateType.F90
  src/biogeophys/CanopyStateType.F90
Labels: priority: high, type: code cleanup/docs

#398 Allow first history tape to have other than one time point per file
  src/main/controlMod.F90
  src/main/histFileMod.F90
Labels: priority: high, type: enhance - science

#422 Work on templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01_bug_report.md
  .github/ISSUE_TEMPLATE/02_support_needed.md
  .github/ISSUE_TEMPLATE/03_science_discussion.md
  .github/ISSUE_TEMPLATE/04_other.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: tag: simple bfb, type: docs - non-code

#416 Start a document of design notes
  doc/design/oo_design.rst
Labels: type: docs - non-code
