Repository ESCOMP/CTSM, pull requests merged in 2018-09, with the labels that each got.

#496 Updating default FATES parameter file
  bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: PR: FATES change

#522 Point to the new ndep historical file for all cases, also update cime…
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/use_cases/1850-2100_rcp2.6_transient.xml
  bld/namelist_files/use_cases/1850-2100_rcp4.5_transient.xml
  bld/namelist_files/use_cases/1850-2100_rcp6_transient.xml
  bld/namelist_files/use_cases/1850-2100_rcp8.5_transient.xml
  bld/namelist_files/use_cases/1850_control.xml
  bld/namelist_files/use_cases/2000-2100_rcp8.5_transient.xml
  bld/namelist_files/use_cases/20thC_transient.xml
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
Labels: priority: high, status: work in progress, type: enhance - science

#462 Add namelist item to calculate all heat stress indices only if requested; to speed up model
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/HumanIndexMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/UrbanFluxesMod.F90
Labels: priority: low, status: ready, type: enhance - software

#517 Updated path to fates default parameter file
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: PR: FATES change, status: ready

#449 Bring in snowmip diagnostic fields
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm50KSinkMOut/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm50KitchenSink/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/default/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/reduceOutput/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/README
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/CMakeLists.txt
  src/biogeophys/CanopyHydrologyMod.F90
  src/biogeophys/HumanIndexMod.F90
  src/biogeophys/IrrigationMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SolarAbsorbedType.F90
  src/biogeophys/SurfaceAlbedoMod.F90
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/SurfaceRadiationMod.F90
  src/biogeophys/UrbanFluxesMod.F90
  src/biogeophys/UrbanRadiationMod.F90
  src/biogeophys/test/Balance_test/CMakeLists.txt
  src/biogeophys/test/Balance_test/test_Balance.pf
  src/biogeophys/test/CMakeLists.txt
  src/biogeophys/test/Irrigation_test/test_irrigation.pf
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/surfrdMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
  src/unit_test_stubs/main/GetGlobalValuesMod_stub.F90
  src/unit_test_stubs/main/ncdio_pio_fake.F90.in
  src/utils/clm_time_manager.F90
  src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
  tools/mkmapdata/mkmapdata.sh
  tools/mkmapdata/regridbatch.sh
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/src/mksurfdat.F90
  tools/mksurfdata_map/src/mktopostatsMod.F90
  tools/ncl_scripts/getco2_historical.ncl
Labels: priority: high, status: ready, type: enhance - science
