Repository ESCOMP/CTSM, pull requests merged in 2018-11, with the labels that each got.

#548 fates refactor of 3d arrays in restart - api changes
  src/utils/clmfates_interfaceMod.F90
Labels: PR: FATES Next API, status: ready

#559 Updated fates external tag
  Externals_CLM.cfg
Labels: status: ready

#563 Update externals (cime, mosart, rtm) for release branch, add new science support compsets/tests
  Externals.cfg
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
Labels: priority: high, status: ready, type: enhance - science, type: enhance - software, type: tests

#483 Collapse2gencrop branch: Allow the model to not need to read 16-pft datasets and rather read 78-pft datasets
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_f10/README
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_f10/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_f10/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/glcMEC_decrease/README
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNDVDriverMod.F90
  src/biogeochem/CNDVType.F90
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNFireEmissionsMod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNPrecisionControlMod.F90
  src/biogeochem/DUSTMod.F90
  src/biogeochem/SatellitePhenologyMod.F90
  src/biogeochem/VOCEmissionMod.F90
  src/biogeochem/dynCNDVMod.F90
  src/biogeochem/dynConsBiogeochemMod.F90
  src/biogeochem/dynHarvestMod.F90
  src/biogeophys/LakeCon.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/cpl/lnd_comp_mct.F90
  src/dyn_subgrid/dyncropFileMod.F90
  src/dyn_subgrid/dynpftFileMod.F90
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varcon.F90
  src/main/clm_varpar.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/main/initGridCellsMod.F90
  src/main/pftconMod.F90
  src/main/subgridAveMod.F90
  src/main/surfrdMod.F90
  src/main/surfrdUtilsMod.F90
  src/main/test/surfrdUtils_test/test_surfrdUtils.pf
  src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90
  src/soilbiogeochem/SoilBiogeochemVerticalProfileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: status: ready, tag: simple bfb, type: code cleanup/docs, type: enhance - software, type: tests

#579 Fix bug in XML for surface dataset for f05 1850 non-crop
  Externals.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
Labels: priority: high, status: ready, type: bug - other
