Repository ESCOMP/CTSM, pull requests merged in 2018-07, with the labels that each got.

#437 ChangeLog: ask about significant changes to various configurations
  doc/.ChangeLog_template
Labels: type: docs - non-code

#405 Protected fates calculation of bare-soil area to not go below 0
  src/utils/clmfates_interfaceMod.F90
Labels: PR: FATES change

#338 Radtemp
  .CTSMTrunkChecklist
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/usermods_dirs/cmip6_output/user_nl_clm
  doc/.ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/HydrologyNoDrainageMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SoilFluxesMod.F90
  src/biogeophys/TemperatureType.F90
  src/cpl/lnd_import_export.F90
  src/main/clm_driver.F90
  src/main/controlMod.F90
Labels: priority: high, type: enhance - science

#445 Move ctsm1.0.dev004 to CLM5.0 release branch
  .CTSMTrunkChecklist
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01_bug_report.md
  .github/ISSUE_TEMPLATE/02_support_needed.md
  .github/ISSUE_TEMPLATE/03_science_discussion.md
  .github/ISSUE_TEMPLATE/04_other.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CONTRIBUTING.md
  Externals.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/use_cases/1850_control.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/DA_multidrv/user_nl_clm_0001
  cime_config/testdefs/testmods_dirs/clm/DA_multidrv/user_nl_clm_0002
  cime_config/usermods_dirs/cmip6_output/user_nl_clm
  doc/.ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  doc/design/oo_design.rst
  doc/release-clm5.0.ChangeLog
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/HydrologyNoDrainageMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SoilFluxesMod.F90
  src/biogeophys/TemperatureType.F90
  src/cpl/lnd_import_export.F90
  src/main/clm_driver.F90
  src/main/controlMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
  test/tools/README
  test/tools/TCBCFGtools.sh
  test/tools/input_tests_master
  test/tools/test_driver.sh
  tools/mkprocdata_map/src/Makefile.common
  tools/mksurfdata_map/Makefile.data
  tools/mksurfdata_map/src/Makefile.common
  tools/mksurfdata_map/src/mkpctPftTypeMod.F90
  tools/mksurfdata_map/src/mkpftMod.F90
  tools/mksurfdata_map/src/mksurfdat.F90
Labels: priority: high

#448 Update fates default parameter file
  bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: PR: FATES Next API
