Repository ESCOMP/CTSM, pull requests merged in 2018-05, with the labels that each got.

#376 Changes needed for DART, to bypass balance checks when DA is done
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/pauseResume/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/pauseResume/shell_commands
  src/biogeophys/BalanceCheckMod.F90
  src/cpl/lnd_comp_mct.F90
  src/utils/clm_time_manager.F90
  src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
Labels: priority: high, type: enhance - science

#381 1850 fully coupled ndep update, update cism, update PE layouts, turn BFBFLAG on for testing
  Externals.cfg
  bld/namelist_files/use_cases/1850_control.xml
  cime_config/config_pes.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Fates/shell_commands
  cime_config/testdefs/testmods_dirs/clm/af_bias_v7/shell_commands
  cime_config/testdefs/testmods_dirs/clm/cmip6/shell_commands
  cime_config/testdefs/testmods_dirs/clm/default/shell_commands
  cime_config/testdefs/testmods_dirs/clm/irrigOn_reduceOutput/shell_commands
  cime_config/testdefs/testmods_dirs/clm/nofire/shell_commands
  cime_config/testdefs/testmods_dirs/clm/oldhyd/shell_commands
  cime_config/testdefs/testmods_dirs/clm/rad_hrly_light_res_half/shell_commands
  cime_config/testdefs/testmods_dirs/clm/reduceOutput/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/SoilHydrologyInitTimeConstMod.F90
  test/tools/test_driver.sh
  tools/mkmapdata/mkmapdata.sh
Labels: priority: high, type: enhance - science

#391 fates hydro compatibility
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/testdefs/testmods_dirs/clm/Fates/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesAllVars/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesHydro/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesHydro/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesLogging/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesNoFire/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesPPhys/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesST3/include_user_mods
  src/utils/clmfates_interfaceMod.F90
Labels: type: FATES change

#350 Add science_support for more compsets
  cime_config/config_compsets.xml
Labels: priority: high, type: docs - non-code
