Repository ESCOMP/CTSM, pull requests merged in 2018-10, with the labels that each got.

#525 Update trunk checklist
  .CTSMTrunkChecklist
  CTSMMasterChecklist
  doc/.ChangeLog_template
Labels: type: docs - non-code

#543 Update release branch to ctsm1.0.dev012
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  bld/namelist_files/use_cases/1850_control.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm50KSinkMOut/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm50KitchenSink/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/default/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/reduceOutput/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/README
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CMakeLists.txt
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/CanopyHydrologyMod.F90
  src/biogeophys/HumanIndexMod.F90
  src/biogeophys/IrrigationMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SolarAbsorbedType.F90
  src/biogeophys/SurfaceAlbedoMod.F90
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/SurfaceRadiationMod.F90
  src/biogeophys/UrbanFluxesMod.F90
  src/biogeophys/UrbanRadiationMod.F90
  src/biogeophys/WaterfluxType.F90
  src/biogeophys/test/Balance_test/CMakeLists.txt
  src/biogeophys/test/Balance_test/test_Balance.pf
  src/biogeophys/test/CMakeLists.txt
  src/biogeophys/test/Irrigation_test/test_irrigation.pf
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/surfrdMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
  src/unit_test_stubs/main/GetGlobalValuesMod_stub.F90
  src/unit_test_stubs/main/ncdio_pio_fake.F90.in
  src/utils/clm_time_manager.F90
  src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
  tools/mkmapdata/mkmapdata.sh
  tools/mkmapdata/regridbatch.sh
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/src/mksurfdat.F90
  tools/mksurfdata_map/src/mktopostatsMod.F90
  tools/ncl_scripts/getco2_historical.ncl
Labels: priority: high, status: ready, type: code cleanup/docs

#537 Fates parteh api
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/configure
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  cime_config/buildlib
  cime_config/testdefs/testmods_dirs/clm/FatesAllVars/user_nl_clm
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: PR: FATES Next API, status: ready

#546 Add in ability for mksurfdata_map to handle ssp_rcp scenarios and specifically SSP5-8.5
  bld/namelist_files/createMkSrfEntry.py
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/nl_files/mksrfdt_1x1_numaIA_crp_SSP5-8.5_1850-2100
  test/tools/tests_posttag_nompi_regression
  test/tools/tests_pretag_cheyenne_nompi
  tools/mksurfdata_map/mksurfdata.pl
Labels: priority: high, status: ready, type: enhance - science

#540 Transient pft issue #538
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_definition_clm4_5.xml
  bld/unit_testers/build-namelist_test.pl
  doc/ChangeLog
  doc/ChangeSum
  src/dyn_subgrid/dynSubgridControlMod.F90
  src/dyn_subgrid/dyncropFileMod.F90
Labels: priority: high, severity: critical, status: ready, type: bug - impacts science

#527 Add carbon_isotope user-mod directory to turn on c13 and c14
  cime_config/usermods_dirs/carbon_isotopes/user_nl_clm
  cime_config/usermods_dirs/cmip6/include_user_mods
Labels: priority: high, status: work in progress, type: enhance - science

#539 Support a %CMIP6DECK compset modifier
  cime_config/config_component.xml
Labels: status: work in progress

#552 Move fix for transient non-crop to release-clm5.0 branch
  .CTSMTrunkChecklist
  CTSMMasterChecklist
  bld/CLMBuildNamelist.pm
  bld/namelist_files/createMkSrfEntry.py
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  bld/unit_testers/build-namelist_test.pl
  doc/.ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  src/dyn_subgrid/dynSubgridControlMod.F90
  src/dyn_subgrid/dyncropFileMod.F90
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/nl_files/mksrfdt_1x1_numaIA_crp_SSP5-8.5_1850-2100
  test/tools/tests_posttag_nompi_regression
  test/tools/tests_pretag_cheyenne_nompi
  tools/mksurfdata_map/mksurfdata.pl
Labels: priority: high, severity: critical, status: ready
