Repository ESCOMP/CTSM, pull requests merged in 2019-04, with the labels that each got.

#676 12 PFT FATES default file
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  src/biogeophys/CanopyFluxesMod.F90
Labels: PR status: ready, branch tag: FATES Next API

#679 Re-fixing mfilt fix to the fates_next_api branch
  src/main/controlMod.F90
  src/main/histFileMod.F90
Labels: PR status: ready, branch tag: FATES change

#641 Ability to remove individual landunits for faster runs
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/README
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/rm_indiv_lunits_and_collapse_to_dom/README
  cime_config/testdefs/testmods_dirs/clm/rm_indiv_lunits_and_collapse_to_dom/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/rm_indiv_lunits_and_collapse_to_dom/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/dyn_subgrid/dynSubgridControlMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/surfrdMod.F90
  src/main/surfrdUtilsMod.F90
  src/main/test/surfrdUtils_test/test_surfrdUtils.pf
Labels: PR status: ready, type: enhance - software, type: tests

#694 Fix for the Carbon isotope land-use change bug
  Externals.cfg
  README
  cime_config/SystemTests/lciso.py
  cime_config/config_tests.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/joblauncher/job_launcher_qsub.py
  src/biogeochem/CNVegetationFacade.F90
Labels: PR status: ready, priority: high, severity: critical, type: bug - impacts science

#696 Use universal_newlines in call to subprocess.Popen
  python/ctsm/joblauncher/job_launcher_qsub.py
Labels: PR status: ready
