Repository ESCOMP/CTSM, pull requests merged in 2019-01, with the labels that each got.

#601 Print git status and related info when running run_sys_tests
  .gitignore
  python/ctsm/joblauncher/job_launcher_no_batch.py
  python/ctsm/run_sys_tests.py
  python/ctsm/test/joblauncher/test_job_launcher_no_batch.py
  python/ctsm/test/test_run_sys_tests.py
Labels: status: ready

#568 Updated interface to accomodate fixes to fates-hydro
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesHydro/user_nl_clm
  src/main/clm_instMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: PR: FATES Next API

#616 No anthro options to tools, and all future scenarios in place, plus a few small issue fixes
  .gitignore
  bld/CLMBuildNamelist.pm
  bld/namelist_files/createMkSrfEntry.py
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  bld/namelist_files/namelist_definition_clm4_0.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  bld/unit_testers/build-namelist_test.pl
  tools/mksurfdata_map/README.developers
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/src/mksurfdat.F90
Labels: priority: high, status: ready, type: enhance - science, type: enhance - software

#551 Add history fields for vertically-resolved sums of SOIL1C, SOIL2C, SO…
  cime_config/usermods_dirs/_includes/cmip6_carbon_isotopes/user_nl_clm
  cime_config/usermods_dirs/output_bgc/user_nl_clm
  src/soilbiogeochem/SoilBiogeochemCarbonStateType.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenStateType.F90
Labels: status: ready, tag: simple bfb

#626 Initial add of a contributor tool directory for various scripts
  README
  tools/README
  tools/contrib/README
  tools/contrib/SpinupStability.ncl
  tools/contrib/modify_singlept_site
  tools/contrib/run_clm_historical
  tools/contrib/run_clmtowers
  tools/contrib/singlept
  tools/contrib/subset_surfdata
Labels: PR status: work in progress, PR tag: no testing required, priority: high, type: enhance - software
