Repository ESCOMP/CTSM, pull requests merged in 2019-03, with the labels that each got.

#656 Update to cime version that works on cheyenne after the mar/5th/2019 downtime
  Externals.cfg
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
Labels: PR status: ready, priority: high, severity: critical, type: enhance - software

#611 Reseed generic crops and increase totvegc threshold from 0 to 1 (see issue #608)
  src/biogeochem/CNVegCarbonStateType.F90
Labels: type: bug - impacts science

#625 Qsnoevapfix
  src/biogeophys/WaterfluxType.F90
Labels: PR status: ready, priority: high, type: bug - impacts science

#669 Get fates_next_api working
  Externals.cfg
  Externals_CLM.cfg
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
Labels: PR status: ready, PR tag: FATES Next API, type: tests
