Repository ESCOMP/CTSM, pull requests merged in 2019-02, with the labels that each got.

#583 Add routine to find indices of max k values in data
  src/utils/array_utils.F90.in
  src/utils/test/CMakeLists.txt
  src/utils/test/array_utils_test/CMakeLists.txt
  src/utils/test/array_utils_test/test_find_k_max_indices.pf
Labels: PR status: ready

#588 NWP collapse pfts to the N most dominant
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/collapse_nat_pfts_decStart/README
  cime_config/testdefs/testmods_dirs/clm/collapse_nat_pfts_decStart/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/collapse_nat_pfts_decStart/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_decStart_f10/README
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_decStart_f10/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_decStart_f10/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_f10/include_user_mods
  doc/ChangeLog
  doc/ChangeSum
  src/dyn_subgrid/dyncropFileMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/surfrdMod.F90
  src/main/surfrdUtilsMod.F90
  src/main/test/surfrdUtils_test/test_surfrdUtils.pf
  src/utils/array_utils.F90.in
  src/utils/test/array_utils_test/test_find_k_max_indices.pf
Labels: PR status: ready, type: enhance - software, type: tests

#368 Allow FATES to run with inventory initialization files
  bld/CLMBuildNamelist.pm
Labels: PR status: later, PR tag: FATES change

#632 update default fates parameter file
  bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: PR tag: FATES Next API

#634 Remove some of the fields from the surface dataset creation
  test/tools/nl_files/mksrfdt_10x15_1850
  tools/mksurfdata_map/Makefile.data
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/src/Srcfiles
  tools/mksurfdata_map/src/mkCH4inversionMod.F90
  tools/mksurfdata_map/src/mkfileMod.F90
  tools/mksurfdata_map/src/mkglcmecMod.F90
  tools/mksurfdata_map/src/mksurfdat.F90
  tools/mksurfdata_map/src/mkvarctl.F90
Labels: PR status: ready, priority: high, type: enhance - software

#639 Allow collapsing to N dominant landunits
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/README
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/collapse_to_dominant_decStart/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/surfrdMod.F90
  src/main/surfrdUtilsMod.F90
  src/main/test/surfrdUtils_test/test_surfrdUtils.pf
Labels: PR status: ready, type: enhance - software
