Repository ESCOMP/CTSM, pull requests merged in 2020-04, with the labels that each got.

#959 Add surface datasets/landuse-timeseries/compsets/use-cases for extensions to 2300
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/use_cases/2100-2300_SSP1-2.6_transient.xml
  bld/namelist_files/use_cases/2100-2300_SSP5-3.4_transient.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/usermods_dirs/cmip6_waccm_deck/shell_commands
  doc/.release-ChangeLog_template
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  tools/mksurfdata_map/mksurfdata.pl
Labels: branch tag: release, priority: high, tag: enh - new science, type: enhancement

#971 Fix bug in snow aerosol numerics (causes occasional HUGE aerosol values)
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/SnowHydrologyMod.F90
Labels: PR status: ready

#975 Fix irrigation for 2300 extensions
  bld/namelist_files/namelist_defaults_clm4_5.xml
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  src/biogeochem/CNVegStateType.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/WaterfluxType.F90
  tools/contrib/singlept
  tools/contrib/ssp_anomaly_forcing_smooth
Labels: branch tag: release, priority: high, tag: bug - critical, tag: bug - impacts science, type: bug

#977 Add DOI badge
  README.rst
Labels: PR status: ready, PR tag: no testing required

#986 Fix issues with no-anthro surface dataset creation
  bld/namelist_files/namelist_defaults_clm4_5_tools.xml
  cime_config/SystemTests/ssp.py
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/nl_files/mksrfdt_f09_PtVg
  test/tools/tests_pretag_cheyenne_nompi
  tools/mksurfdata_map/mksurfdata.pl
Labels: type: bug

#929 fates hydro refactors
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
  cime_config/testdefs/testmods_dirs/clm/FatesHydro/user_nl_clm
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/SoilStateType.F90
  src/biogeophys/WaterStateType.F90
  src/utils/clmfates_interfaceMod.F90
Labels: branch tag: FATES Next API

#989 Increase tolerance on near-zero truncation in UpdateState_TopLayerFluxes
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/SnowHydrologyMod.F90
  src/utils/NumericsMod.F90
  src/utils/test/numerics_test/test_truncate_small_values.pf
Labels: PR status: ready

#996 Update cime to latest cesm2.2 beta tag
  Externals.cfg
  cime_config/SystemTests/ssp.py
  doc/ChangeLog
  doc/ChangeSum
  manage_externals/.travis.yml
  manage_externals/README.md
  manage_externals/manic/checkout.py
  manage_externals/manic/externals_description.py
  manage_externals/manic/repository.py
  manage_externals/manic/repository_factory.py
  manage_externals/manic/repository_git.py
  manage_externals/manic/repository_svn.py
  manage_externals/manic/sourcetree.py
  manage_externals/test/repos/simple-ext.git/objects/14/2711fdbbcb8034d7cad6bae6801887b12fe61d
  manage_externals/test/repos/simple-ext.git/objects/60/7ec299c17dd285c029edc41a0109e49d441380
  manage_externals/test/repos/simple-ext.git/objects/b7/692b6d391899680da7b9b6fd8af4c413f06fe7
  manage_externals/test/repos/simple-ext.git/objects/d1/163870d19c3dee34fada3a76b785cfa2a8424b
  manage_externals/test/repos/simple-ext.git/objects/d8/ed2f33179d751937f8fde2e33921e4827babf4
  manage_externals/test/repos/simple-ext.git/refs/heads/master
  manage_externals/test/repos/simple-ext.git/refs/tags/tag2
  manage_externals/test/test_sys_checkout.py
  manage_externals/test/test_unit_externals_description.py
  manage_externals/test/test_unit_repository.py
  manage_externals/test/test_unit_repository_git.py
  src/biogeochem/CNVegStateType.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/WaterFluxType.F90
Labels: type: enhancement

#998 Remove Copyright file
  Copyright
Labels: PR status: ready, PR tag: no testing required
