Repository ESCOMP/CTSM, pull requests merged in 2020-05, with the labels that each got.

#999 Remove Copyright file
  Copyright
Labels: PR status: ready, PR tag: no testing required

#567 Add a bunch of ignore patterns for vim
  .gitignore
Labels: PR status: ready, type: documentation

#561 Add list of checks that should be done when making new surface datasets
  tools/mksurfdata_map/README.developers
Labels: PR status: ready, type: documentation

#564 Update mksurfdata_map to include glaciers outside of pft landmask
  tools/mksurfdata_map/src/mksurfdat.F90
Labels: PR status: ready, priority: high, type: enhancement

#907 Adjusting regression test definitions
  cime_config/testdefs/testlist_clm.xml
Labels: PR status: work in progress, branch tag: FATES change, type: tests

#1011 Changed user_nl_clm fire variables to uppercase for FATES test suite
  Externals_CLM.cfg
  cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdDef/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesShortList/user_nl_clm
Labels: branch tag: FATES Next API, type: tests

#1007 fates interface refactor (fix circular deps)
  Externals_CLM.cfg
  src/main/clm_initializeMod.F90
  src/main/decompInitMod.F90
  src/main/histFileMod.F90
  src/main/subgridMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: branch tag: FATES Next API

#1006 Document authorship and CTSM code management team
  .zenodo.json
  README.md
  README.rst
Labels: PR status: ready, PR tag: no testing required

#1009 Point to list of common problems in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR status: ready, PR tag: no testing required

#891 add definitions/defaults for GFDL fv3 cubed sphere grids C24, C48, C96, C192, C384
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_pes.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  tools/mksurfdata_map/Makefile.data
Labels: PR status: work in progress, type: enhancement
