Repository ESCOMP/CTSM, pull requests merged in 2020-06, with the labels that each got.

#1027 Updating FATES default parameter file to api 11.1
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_clm4_5.xml
Labels: branch tag: FATES change

#985 Fixed Biogeeography: FATES_NEXT_API
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/namelist_definition_clm4_5.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesReducedComplexFixedBiogeo/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesReducedComplexFixedBiogeo/user_nl_clm
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: branch tag: FATES Next API, tag: enh - new science, type: enhancement

#1033 Updating pointer to new fates tag for fixed biogeography update
  Externals_CLM.cfg
Labels: branch tag: FATES Next API, priority: high

#1039 Move some hardcoded parameters to the paramsfile
  bld/namelist_files/namelist_defaults_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireMethodMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/HydrologyDrainageMod.F90
  src/biogeophys/HydrologyNoDrainageMod.F90
  src/biogeophys/InfiltrationExcessRunoffMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SnowHydrologyMod.F90
  src/biogeophys/SoilHydrologyMod.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/biogeophys/SoilWaterMovementMod.F90
  src/biogeophys/SurfaceWaterMod.F90
  src/biogeophys/UrbanFluxesMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varcon.F90
  src/main/controlMod.F90
  src/main/readParamsMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemLittVertTranspMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
Labels: priority: high, tag: enh - new science, type: enhancement

#1034 Building energy fix (issue #803).
  src/biogeophys/UrbBuildTempOleson2015Mod.F90
Labels: tag: bug - impacts science

#961 Fixes for the LUNA dayl bugs
  bld/namelist_files/namelist_defaults_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/soilbiogeochem/SoilBiogeochemPrecisionControlMod.F90
Labels: PR status: ready, tag: bug - impacts science
