Repository ESCOMP/CTSM, pull requests merged in 2020-11, with the labels that each got.

#1180 Pass temperature and moisture scalars as boundary condition inputs for fragmentation scalar calculation
  Externals_CLM.cfg
  src/utils/clmfates_interfaceMod.F90
Labels: branch tag: FATES Next API

#1015 Document authorship and CTSM code management team, release branch
  .zenodo.json
  README.md
Labels: PR status: ready, PR tag: no testing required

#1223 Update troubleshooting chapter in User's Guide for poi code
  doc/source/users_guide/trouble-shooting/trouble-shooting.rst
Labels: type: documentation
