Repository ESCOMP/CTSM, pull requests merged in 2020-09, with the labels that each got.

#1102 Some bit-for-bit changes needed for the Perturbed Parameter Ensemble work
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFireBaseMod.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
Labels: tag: simple bfb, type: enhancement

#1146 Add --project argument to LILAC's create_newcase command
  python/ctsm/lilac_build_ctsm.py
Labels: PR status: ready, priority: high, tag: bug - critical

#1149 LILACSMOKE: Call case.load_env() before building the atm driver
  cime_config/SystemTests/lilacsmoke.py
Labels: PR status: ready, PR tag: no testing required

#1157 Urban mksurfdata update
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  tools/mksurfdata_map/mksurfdata_map.namelist
  tools/mksurfdata_map/src/mkfileMod.F90
  tools/mksurfdata_map/src/mkurbanparMod.F90
  tools/mksurfdata_map/src/mkvarctl.F90
  tools/mksurfdata_map/src/mkvarpar.F90
Labels: type: enhancement

#1151 Have a copy of btran2 that's just inside CNFire
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/EnergyFluxType.F90
  src/biogeophys/SoilMoistStressMod.F90
  src/main/FireDataBaseType.F90
  src/main/FireMethodType.F90
  src/main/clm_driver.F90
  src/utils/clmfates_interfaceMod.F90
Labels: PR status: work in progress, priority: high, tag: simple bfb, type: code cleanup, type: enhancement

#1150 clm5_1 physics starting point
  .config_files.xml
  .gitignore
  bld/CLMBuildNamelist.pm
  bld/config_files/clm_phys_vers.pm
  bld/config_files/config_definition_ctsm.xml
  bld/listDefaultNamelist.pl
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_drydep.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/use_cases/1850_control.xml
  bld/namelist_files/use_cases/1850_noanthro_control.xml
  bld/namelist_files/use_cases/2000_control.xml
  bld/namelist_files/use_cases/2010_control.xml
  bld/namelist_files/use_cases/20thC_transient.xml
  bld/namelist_files/use_cases/stdurbpt_pd.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/lciso.py
  cime_config/SystemTests/lii.py
  cime_config/SystemTests/lii2finidatareas.py
  cime_config/SystemTests/soilstructud.py
  cime_config/buildlib
  cime_config/buildnml
  cime_config/config_archive.xml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  lilac/bld_templates/ctsm_template.cfg
  python/ctsm/lilac_make_runtime_inputs.py
  src/biogeochem/CNDVDriverMod.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireFactoryMod.F90
  src/biogeochem/CNFireLi2021Mod.F90
  src/biogeophys/SoilMoistStressMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/main/pftconMod.F90
  src/main/restFileMod.F90
  tools/contrib/SpinupStability.ncl
  tools/contrib/run_clm_historical
Labels: PR status: ready, priority: high, tag: enh - new science, type: enhancement

#1094 Make most QSat output arguments optional
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/QSatMod.F90
  src/biogeophys/SurfaceHumidityMod.F90
  src/biogeophys/UrbanFluxesMod.F90
  src/biogeophys/test/HumanStress_test/test_humanstress.pf
  src/main/atm2lndMod.F90
Labels: PR status: ready

#1148 Nutrient enabled FATES API
  Externals_CLM.cfg
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesPRT2/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesPRT2/user_nl_clm
  src/biogeochem/EDBGCDynMod.F90
  src/main/clm_driver.F90
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
  src/utils/clmfates_paraminterfaceMod.F90
Labels: branch tag: FATES Next API

#1165 Fix issue#1163
  src/biogeochem/CNPhenologyMod.F90
Labels: tag: bug - critical
