Repository ESCOMP/CTSM, pull requests merged in 2020-08, with the labels that each got.

#1079 Bit-for-bit updates for the CESM2.2.0 release
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/use_cases/2010_control.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm45cam6LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm45cam6LndTuningMode/shell_commands
  cime_config/usermods_dirs/cmip6_waccm_deck/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireFactoryMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireNoFireMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/main/FireDataBaseType.F90
  src/main/FireMethodType.F90
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/nl_files/mksrfdt_f09_PtVg
  test/tools/tests_pretag_cheyenne_nompi
  tools/contrib/README
  tools/contrib/singlept
  tools/contrib/ssp_anomaly_forcing_smooth
  tools/mkmapgrids/mkscripgrid.ncl
  tools/mksurfdata_map/README
  tools/mksurfdata_map/mksurfdata.pl
Labels: PR status: work in progress, priority: high, tag: simple bfb, type: code cleanup

#1100 Answer changes needed for CESM2.2.0
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/use_cases/2010_control.xml
  bld/namelist_files/use_cases/20thC_transient.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline2005Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline2005Start/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNVegCarbonStateType.F90
  src/main/restFileMod.F90
Labels: PR status: work in progress, priority: high, tag: bug - impacts science

#1111 Adjust FV3/SE PE layouts
  Externals.cfg
  Externals_cime.cfg
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
  doc/ChangeLog
  doc/ChangeSum
Labels: priority: high, type: enhancement

#1124 Merge ctsm1.0.dev095 tag into fates_main_api
  .github/PULL_REQUEST_TEMPLATE.md
  .zenodo.json
  Externals.cfg
  Externals_cime.cfg
  README.md
  README.rst
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  manage_externals/manic/externals_description.py
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireFactoryMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireMethodMod.F90
  src/biogeochem/CNFireNoFireMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/FATESFireDataMod.F90
  src/biogeochem/FATESFireNoDataMod.F90
  src/biogeochem/ch4Mod.F90
  src/main/histFileMod.F90
Labels: branch tag: FATES Next API

#1114 Update cime so default end year for GSWP3 forcing is 2013 and change prevyr default for vcmax/jmax
  Externals.cfg
  Externals_cime.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  bld/unit_testers/xFail/expectedFail.pm
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/lilac_build_ctsm.py
  src/biogeophys/PhotosynthesisMod.F90
Labels: PR status: work in progress, priority: high, tag: bug - impacts science, type: enhancement

#1120 Record run_sys_tests command-line
  python/ctsm/run_sys_tests.py
Labels: PR status: ready, PR tag: no testing required

#1122 updates to current surfdata & landuse files in tools/contrib
  tools/contrib/singlept
Labels: PR tag: no testing required, tag: support tools only

#1119 Move mksurfdata_map rounding of special landunits to before wetland fill
  tools/mksurfdata_map/README.developers
  tools/mksurfdata_map/src/mksurfdat.F90
Labels: PR status: ready
