Repository ESCOMP/CTSM, pull requests merged in 2020-10, with the labels that each got.

#1177 Two answer changes turn dribble_crophrv_xsmrpool_2atm and correct clm5_1 finidat file for 2000 conditions
  bld/namelist_files/namelist_defaults_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
Labels: PR status: ready, tag: bug - impacts science

#1187 Some BFB changes and Hydraulic redistribution
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SoilWaterPlantSinkMod.F90
  src/biogeophys/WaterFluxBulkType.F90
  src/main/clm_varpar.F90
  src/main/controlMod.F90
Labels: PR status: ready, tag: simple bfb, type: enhancement

#1126 Hydraulic redistribution
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/SoilWaterPlantSinkMod.F90
  src/biogeophys/WaterFluxBulkType.F90
Labels: PR status: ready, tag: enh - new science, tag: simple bfb, type: enhancement
