Repository ESCOMP/CTSM, pull requests merged in 2021-04, with the labels that each got.

#990 Arctic changes branch with Kattge in place of Leuning in LUNA
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNSharedParamsMod.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/TemperatureType.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
  src/biogeophys/WaterType.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/initVerticalMod.F90
  src/main/pftconMod.F90
Labels: PR status: ready, priority: high, tag: enh - new science, type: enhancement

#1324 HLM-side changes to allow FATES snow occlusion of LAI
  Externals_CLM.cfg
  doc/ChangeLog
  doc/ChangeSum
  src/utils/clmfates_interfaceMod.F90
Labels: FATES update requiring an API change, priority: high

#1179 Bring in changes from release-cesm2.2.01 to main-development
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/config_compsets.xml
  doc/.release-ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  doc/UpdateChangelog.pl
  doc/release-cesm2.2.ChangeLog
  test/tools/README
  test/tools/input_tests_master
  test/tools/tests_posttag_izumi_nompi
  test/tools/tests_posttag_nompi_regression
  tools/mkmapdata/mkmapdata.sh
Labels: PR status: ready, type: enhancement
