Repository ESCOMP/CTSM, pull requests merged in 2021-07, with the labels that each got.

#1414 Fates api16.1 (parameter file updates)
  Externals_CLM.cfg
  bld/namelist_files/createMkSrfEntry.py
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/buildlib
  cime_config/buildnml
  doc/ChangeLog
  doc/ChangeSum
Labels: FATES update requiring an API change

#1420 Remove requirement for mct in main ctsm code base other than mct cap
  doc/ChangeLog
  doc/ChangeSum
  src/cpl/lilac/lnd_comp_esmf.F90
  src/cpl/mct/FireDataBaseType.F90
  src/cpl/mct/SoilMoistureStreamMod.F90
  src/cpl/mct/UrbanTimeVarType.F90
  src/cpl/mct/ch4FInundatedStreamType.F90
  src/cpl/mct/laiStreamMod.F90
  src/cpl/mct/lnd_comp_mct.F90
  src/cpl/mct/lnd_set_decomp_and_domain.F90
  src/cpl/mct/ndepStreamMod.F90
  src/cpl/nuopc/lnd_comp_nuopc.F90
  src/cpl/share_esmf/lnd_set_decomp_and_domain.F90
  src/main/GetGlobalValuesMod.F90
  src/main/GridcellType.F90
  src/main/accumulMod.F90
  src/main/clm_initializeMod.F90
  src/main/controlMod.F90
  src/main/decompInitMod.F90
  src/main/decompMod.F90
  src/main/histFileMod.F90
  src/main/initGridCellsMod.F90
  src/main/ncdio_pio.F90.in
  src/main/subgridRestMod.F90
  src/unit_test_shr/unittestSubgridMod.F90
  src/utils/spmdGathScatMod.F90
Labels: PR status: ready, type: code cleanup, type: enhancement

#1413 Make certain history fields descriptive that have been labeled by number since #1340
  cime_config/usermods_dirs/output_bgc/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/users_guide/setting-up-and-running-a-case/master_list_file.rst
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/main/clm_varpar.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
Labels: type: enhancement

#1374 Local solar time option for average flag
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/localtimeOutput/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/localtimeOutput/user_nl_clm
  src/main/histFileMod.F90
Labels: tag: simple bfb, type: enhancement

#1375 Script for modifying neon surface dataset
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/test_driver.sh
  test/tools/tests_pretag_cheyenne_nompi
  tools/contrib/modify_singlept_site_neon.py
Labels: PR status: ready, PR tag: no testing required, tag: support tools only, type: enhancement

#1411 fix stop_option=date, move neon niwo test to match user_mods
  .config_files.xml
  Externals.cfg
  cime_config/buildnml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/NEON_NIWO/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/extra_outputs/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/localtimeOutput/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/localtimeOutput/user_nl_clm
  cime_config/usermods_dirs/NEON/defaults/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/CMakeLists.txt
  src/cpl/nuopc/lnd_comp_nuopc.F90
  src/main/histFileMod.F90
Labels: PR status: ready, type: enhancement

#1439 fix paths to slnd and xlnd in config_files
  .config_files.xml
Labels: PR status: ready, PR tag: no testing required

#1440 Updates to Tech Note Photosynthesis chapter
  doc/source/tech_note/Hydrology/CLM50_Tech_Note_Hydrology.rst
  doc/source/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.rst
Labels: type: documentation
