Repository ESCOMP/CTSM, pull requests merged in 2021-05, with the labels that each got.

#1360 Singlept and regional subsetting script
  tools/contrib/singlept
  tools/contrib/subset_data.py
  tools/contrib/subset_surfdata
Labels: tag: support tools only, type: enhancement

#823 mksurfdata_map: replace source (SRC) files of various masks with SRC files with no mask
  bld/namelist_files/checkmapfiles.ncl
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  doc/ChangeLog
  doc/ChangeSum
  tools/mkmapdata/README
  tools/mkmapdata/mkmapdata.sh
  tools/mkmapdata/regridbatch.sh
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/mksurfdata_map.namelist
  tools/mksurfdata_map/src/mkVICparamsMod.F90
  tools/mksurfdata_map/src/mkagfirepkmonthMod.F90
  tools/mksurfdata_map/src/mkdiagnosticsMod.F90
  tools/mksurfdata_map/src/mkdomainMod.F90
  tools/mksurfdata_map/src/mkgdpMod.F90
  tools/mksurfdata_map/src/mkglacierregionMod.F90
  tools/mksurfdata_map/src/mkglcmecMod.F90
  tools/mksurfdata_map/src/mkgridmapMod.F90
  tools/mksurfdata_map/src/mkharvestMod.F90
  tools/mksurfdata_map/src/mkindexmapMod.F90
  tools/mksurfdata_map/src/mklaiMod.F90
  tools/mksurfdata_map/src/mklanwatMod.F90
  tools/mksurfdata_map/src/mkpeatMod.F90
  tools/mksurfdata_map/src/mkpftMod.F90
  tools/mksurfdata_map/src/mksoilMod.F90
  tools/mksurfdata_map/src/mksoilUtilsMod.F90
  tools/mksurfdata_map/src/mksoildepthMod.F90
  tools/mksurfdata_map/src/mktopostatsMod.F90
  tools/mksurfdata_map/src/mkurbanparCommonMod.F90
  tools/mksurfdata_map/src/mkurbanparMod.F90
  tools/mksurfdata_map/src/mkvocefMod.F90
  tools/mksurfdata_map/src/test/mkgridmap_test/test_mkgridmap.pf
  tools/mksurfdata_map/src/test/mkindexmap_test/test_mkindexmap.pf
Labels: PR status: work in progress, type: enhancement

#1384 Change some constants to double precision, and add some soil limits
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNC14DecayMod.F90
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNDVEstablishmentMod.F90
  src/biogeochem/CNFUNMod.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNProductsMod.F90
  src/biogeochem/DryDepVelocity.F90
  src/biogeochem/NutrientCompetitionCLM45defaultMod.F90
  src/biogeochem/NutrientCompetitionFlexibleCNMod.F90
  src/biogeochem/VOCEmissionMod.F90
  src/biogeophys/ActiveLayerMod.F90
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/BandDiagonalMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/RootBiophysMod.F90
  src/biogeophys/SnowHydrologyMod.F90
  src/biogeophys/SnowSnicarMod.F90
  src/biogeophys/SoilHydrologyInitTimeConstMod.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/biogeophys/SurfaceWaterMod.F90
  src/biogeophys/TemperatureType.F90
  src/main/FuncPedotransferMod.F90
  src/main/clm_varcon.F90
  src/soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
Labels: type: code cleanup, type: enhancement
