Repository ESCOMP/CTSM, pull requests merged in 2021-11, with the labels that each got.

#1530 Add compsets for multiple icesheets
  cime_config/config_compsets.xml
Labels: tag: simple bfb, PR status: ready

#1540 Implement `fates_levleaf` as a FATES 1D dimension variable
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement

#1567 Fix errors in master technical note Eq. 2.3.16
  doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst
Labels: type: documentation

#1568 Fix errors in release technical note Eq. 2.3.16
  doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst
Labels: type: documentation
