Repository ESCOMP/CTSM, pull requests merged in 2021-01, with the labels that each got.

#1231 Merge ctsm1.0.dev113 tag into fates_main_api
  .config_files.xml
  Externals.cfg
  Externals_cime.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/use_cases/20thC_transient.xml
  bld/unit_testers/build-namelist_test.pl
  bld/unit_testers/xFail/expectedFail.pm
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm45cam6LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm45cam6LndTuningMode/shell_commands
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline2005Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/waccmx_offline2005Start/shell_commands
  cime_config/usermods_dirs/cmip6_waccm_deck/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/lilac_build_ctsm.py
  python/ctsm/run_sys_tests.py
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireFactoryMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireNoFireMod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/main/FireDataBaseType.F90
  src/main/FireMethodType.F90
  src/main/histFileMod.F90
  src/main/ncdio_pio.F90.in
  src/main/restFileMod.F90
  src/utils/clmfates_interfaceMod.F90
  test/tools/README.testnames
  test/tools/input_tests_master
  test/tools/nl_files/mksrfdt_f09_PtVg
  test/tools/tests_pretag_cheyenne_nompi
  tools/contrib/README
  tools/contrib/singlept
  tools/contrib/ssp_anomaly_forcing_smooth
  tools/mkmapgrids/mkscripgrid.ncl
  tools/mksurfdata_map/README
  tools/mksurfdata_map/README.developers
  tools/mksurfdata_map/mksurfdata.pl
  tools/mksurfdata_map/src/mksurfdat.F90
Labels: PR status: ready, branch tag: FATES Next API

#1016 Heat storage biomass
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNDVLightMod.F90
  src/biogeochem/CNDVType.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireLi2021Mod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/CNVegNitrogenStateType.F90
  src/biogeochem/CNVegStructUpdateMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/EnergyFluxType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/SoilFluxesMod.F90
  src/biogeophys/TemperatureType.F90
  src/main/clm_varcon.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/pftconMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeCNMod.F90
Labels: PR status: ready, priority: high, tag: enh - new science, type: enhancement

#1227 Update ChangeLog template
  cime_config/testdefs/testlist_clm.xml
  doc/.ChangeLog_template
Labels: PR status: ready, PR tag: no testing required
