Repository ESCOMP/CTSM, pull requests merged in 2021-06, with the labels that each got.

#1340 MIMICS-related refactor before introducing MIMICS
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNC14DecayMod.F90
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNCStateUpdate2Mod.F90
  src/biogeochem/CNCStateUpdate3Mod.F90
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/biogeochem/CNNStateUpdate2Mod.F90
  src/biogeochem/CNNStateUpdate3Mod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/biogeochem/dynConsBiogeochemMod.F90
  src/dyn_subgrid/dynHarvestMod.F90
  src/main/clm_varpar.F90
  src/main/controlMod.F90
  src/main/pftconMod.F90
  src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeCNMod.F90
  src/soilbiogeochem/SoilBiogeochemNStateUpdate1Mod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: PR status: ready, type: code cleanup

#1405 new stream functionality when using NUOPC cap
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/use_cases/1850_noanthro_control.xml
  cime_config/buildnml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testmods_dirs/clm/cplhist/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  lilac/bld_templates/lilac_in_template
  lilac/src/lilac_atmaero.F90
  lilac/src/lilac_mod.F90
  python/ctsm/lilac_make_runtime_inputs.py
  src/biogeochem/SatellitePhenologyMod.F90
  src/cpl/lilac/lnd_comp_esmf.F90
  src/cpl/lilac/lnd_comp_shr.F90
  src/cpl/mct/FireDataBaseType.F90
  src/cpl/mct/SoilMoistureStreamMod.F90
  src/cpl/mct/UrbanTimeVarType.F90
  src/cpl/mct/ch4FInundatedStreamType.F90
  src/cpl/mct/laiStreamMod.F90
  src/cpl/mct/lnd_set_decomp_and_domain.F90
  src/cpl/mct/ndepStreamMod.F90
  src/cpl/share_esmf/FireDataBaseType.F90
  src/cpl/share_esmf/SoilMoistureStreamMod.F90
  src/cpl/share_esmf/UrbanTimeVarType.F90
  src/cpl/share_esmf/ch4FInundatedStreamType.F90
  src/cpl/share_esmf/laiStreamMod.F90
  src/cpl/share_esmf/lnd_set_decomp_and_domain.F90
  src/cpl/share_esmf/ndepStreamMod.F90
  src/main/clm_driver.F90
  src/main/decompInitMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: PR status: ready, type: enhancement

#1400 Include coarse woody debris (CWD) in heterotrophic respiration (HR)
  bld/CLMBuildNamelist.pm
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/README
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompMod.F90
  src/soilbiogeochem/SoilBiogeochemPotentialMod.F90
Labels: branch tag: release, priority: high, tag: enh - new science, tag: next, tag: simple bfb
