Repository ESCOMP/CTSM, pull requests merged in 2021-12, with the labels that each got.

#1536 Refactor static fire data to enable future use of GDP data in SPITFIRE
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireLi2021Mod.F90
  src/biogeochem/CNVegStateType.F90
  src/biogeochem/FATESFireBase.F90
  src/biogeochem/FATESFireDataMod.F90
  src/biogeochem/FATESFireFactoryMod.F90
  src/biogeochem/FATESFireNoDataMod.F90
  src/cpl/mct/FireDataBaseType.F90
  src/cpl/share_esmf/FireDataBaseType.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, type: code cleanup, PR status: ready

#1304 Changes to enable FATES-side running means
  Externals_CLM.cfg
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/CanopyFluxesMod.F90
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, PR status: ready

#1467 improve ui for neon script
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  cime_config/usermods_dirs/NEON/GUAN/shell_commands
  cime_config/usermods_dirs/NEON/LAJA/shell_commands
  cime_config/usermods_dirs/NEON/SJER/shell_commands
  cime_config/usermods_dirs/NEON/TEAK/shell_commands
  cime_config/usermods_dirs/NEON/YELL/shell_commands
  cime_config/usermods_dirs/NEON/defaults/shell_commands
  cime_config/usermods_dirs/NEON/defaults/user_nl_clm
  cime_config/usermods_dirs/NEON/defaults/user_nl_datm_streams
  doc/ChangeLog
  doc/ChangeSum
  doc/source/lilac/obtaining-building-and-running/obtaining-and-building-ctsm.rst
  lilac/bld_templates/config_compilers_template.xml
  lilac/bld_templates/config_machines_template.xml
  lilac/bld_templates/ctsm-build_template.cmake
  python/Makefile
  python/ctsm/.pylintrc
  python/ctsm/lilac_build_ctsm.py
  python/ctsm/test/test_sys_lilac_build_ctsm.py
  python/ctsm/test/test_unit_lilac_build_ctsm.py
  python/pyproject.toml
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/test/Balance_test/test_Balance.pf
  test/tools/README
  test/tools/tests_posttag_hobart_nompi
  test/tools/tests_posttag_izumi_nompi
  test/tools/tests_posttag_nompi_regression
  test/tools/tests_pretag_cheyenne_nompi
  tools/mksurfdata_map/src/Mkdepends
  tools/mksurfdata_map/src/mkVICparamsMod.F90
  tools/mksurfdata_map/src/mkagfirepkmonthMod.F90
  tools/mksurfdata_map/src/mkdiagnosticsMod.F90
  tools/mksurfdata_map/src/mkgdpMod.F90
  tools/mksurfdata_map/src/mkglacierregionMod.F90
  tools/mksurfdata_map/src/mkglcmecMod.F90
  tools/mksurfdata_map/src/mkgridmapMod.F90
  tools/mksurfdata_map/src/mklaiMod.F90
  tools/mksurfdata_map/src/mklanwatMod.F90
  tools/mksurfdata_map/src/mkpeatMod.F90
  tools/mksurfdata_map/src/mkpftMod.F90
  tools/mksurfdata_map/src/mksoilMod.F90
  tools/mksurfdata_map/src/mksoildepthMod.F90
  tools/mksurfdata_map/src/mksurfdat.F90
  tools/mksurfdata_map/src/mktopostatsMod.F90
  tools/mksurfdata_map/src/mkurbanparCommonMod.F90
  tools/mksurfdata_map/src/mkurbanparMod.F90
  tools/site_and_regional/modify_singlept_site_neon.py
  tools/site_and_regional/neon_s3_upload
  tools/site_and_regional/neon_sites_dompft.csv
  tools/site_and_regional/neon_surf_wrapper.py
  tools/site_and_regional/run_neon.py
  tools/site_and_regional/subset_data.py
Labels: type: enhancement

#1576 Update spinup stability scripts
  tools/contrib/README
  tools/contrib/SpinupStability_BGC_v10.ncl
  tools/contrib/SpinupStability_SP_v9.ncl
Labels: PR status: ready, PR tag: no testing required

#1546 Dynamic urban
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/smallville_dynurban_monthly/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/smallville_dynurban_monthly/modify_smallville_with_dynurban.ncl
  cime_config/testdefs/testmods_dirs/clm/smallville_dynurban_monthly/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/design/dynamic_urban.rst
  src/biogeochem/ch4Mod.F90
  src/biogeophys/UrbanParamsType.F90
  src/dyn_subgrid/dynConsBiogeophysMod.F90
  src/dyn_subgrid/dynSubgridControlMod.F90
  src/dyn_subgrid/dynSubgridDriverMod.F90
  src/dyn_subgrid/dynurbanFileMod.F90
Labels: tag: enh - new science
