Repository ESCOMP/CTSM, pull requests merged in 2022-02, with the labels that each got.

#1318 MIMICS into vertically resolved CTSM
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/README
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/mimics/README
  cime_config/testdefs/testmods_dirs/clm/mimics/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/mimics/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/newton_krylov_spinup/README
  cime_config/testdefs/testmods_dirs/clm/newton_krylov_spinup/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/newton_krylov_spinup/user_nl_clm
  cime_config/usermods_dirs/newton_krylov_spinup/README
  cime_config/usermods_dirs/newton_krylov_spinup/shell_commands
  cime_config/usermods_dirs/newton_krylov_spinup/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNBalanceCheckMod.F90
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNFUNMod.F90
  src/biogeochem/CNGRespMod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNNDynamicsMod.F90
  src/biogeochem/CNSharedParamsMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/CNVegNitrogenStateType.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/EDBGCDynMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varcon.F90
  src/main/clm_varpar.F90
  src/main/pftconMod.F90
  src/main/readParamsMod.F90
  src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemCarbonStateType.F90
  src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeConType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenStateType.F90
  src/soilbiogeochem/SoilBiogeochemPotentialMod.F90
  src/soilbiogeochem/SoilBiogeochemStateType.F90
Labels: PR status: ready, tag: enh - new science, tag: large

#1614 add smyle L83 compset and SSP3-7.0 extension
  Externals.cfg
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_clm4_5.xml
  bld/namelist_files/use_cases/1850_smyle_control.xml
  bld/namelist_files/use_cases/20thC_smyle_transient.xml
  bld/namelist_files/use_cases/2100-2300_SSP5-3.4_transient.xml
  bld/namelist_files/use_cases/2100-2300_SSP5-8.5_transient.xml
  bld/namelist_files/use_cases/2100_SSP3-7.0_control.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/smyle_1850/shell_commands
  cime_config/testdefs/testmods_dirs/clm/smyle_hist/shell_commands
  doc/ChangeSum
  doc/release-clm5.0.ChangeLog
  src/main/controlMod.F90
  src/soilbiogeochem/SoilBiogeochemPrecisionControlMod.F90
Labels: type: enhancement, branch tag: release, tag: enh - new science, tag: next

#1215 Fix issue 1191 on release branch
  src/main/controlMod.F90
Labels: PR status: ready, branch tag: release

#1535 Add ventilation flux to urban canyon
  .gitignore
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdDefCH4/README
  cime_config/testdefs/testmods_dirs/clm/FatesColdDefCH4Off/README
  cime_config/testdefs/testmods_dirs/clm/FatesColdDefCH4Off/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdDefCH4Off/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFireEmissionsMod.F90
  src/biogeophys/BalanceCheckMod.F90
  src/biogeophys/EnergyFluxType.F90
  src/biogeophys/SoilFluxesMod.F90
  src/biogeophys/SoilTemperatureMod.F90
  src/biogeophys/UrbBuildTempOleson2015Mod.F90
Labels: tag: bug - impacts science

#1592 Cleaning up fates history interface - soil layers and patch removal
  Externals_CLM.cfg
  cime_config/testdefs/testmods_dirs/clm/FatesColdDefHydro/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/utils/clmfates_interfaceMod.F90
Labels: FATES update requiring an API change

#1615 modify_fsurdat: Add dom_cft as alternative user-choice to dom_nat_pft
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/modify_fsurdat/fsurdat_modifier.py
  python/ctsm/modify_fsurdat/modify_fsurdat.py
  python/ctsm/test/test_sys_fsurdat_modifier.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/test/testinputs/surfdata_5x5_amazon_16pfts_Irrig_CMIP6_simyr2000_c171214_modified_with_crop.nc
  tools/modify_fsurdat/fsurdat_modifier
  tools/modify_fsurdat/modify_template.cfg
Labels: type: enhancement, tag: simple bfb, PR status: ready
