Repository ESCOMP/CTSM, pull requests merged in 2022-07, with the labels that each got.

#1756 Add mksurfdata_esmf system test to test-suite
  cime_config/SystemTests/mksurfdataesmf.py
  cime_config/config_tests.xml
  cime_config/testdefs/testlist_clm.xml
  tools/mksurfdata_esmf/README
  tools/mksurfdata_esmf/gen_mksurfdata_build.sh
  tools/mksurfdata_esmf/gen_mksurfdata_jobscript_multi.py
  tools/mksurfdata_esmf/gen_mksurfdata_jobscript_single.py
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.py
Labels: tag: support tools only

#1770 add checkimport to clm for scam case
  src/cpl/nuopc/lnd_comp_nuopc.F90
Labels: type: enhancement

#1765 Fix missing hostname/CSMDATA in mkmapdata.sh
  tools/mkmapdata/mkmapdata.sh
Labels: type: enhancement

#1577 Apply black to python directory
  .git-blame-ignore-revs
  .github/workflows/black.yml
  python/ctsm/.pylintrc
  python/ctsm/add_cime_to_path.py
  python/ctsm/args_utils.py
  python/ctsm/config_utils.py
  python/ctsm/gen_mksurf_namelist.py
  python/ctsm/git_utils.py
  python/ctsm/joblauncher/job_launcher_base.py
  python/ctsm/joblauncher/job_launcher_factory.py
  python/ctsm/joblauncher/job_launcher_fake.py
  python/ctsm/joblauncher/job_launcher_no_batch.py
  python/ctsm/joblauncher/job_launcher_qsub.py
  python/ctsm/lilac_build_ctsm.py
  python/ctsm/lilac_download_input_data.py
  python/ctsm/lilac_make_runtime_inputs.py
  python/ctsm/machine.py
  python/ctsm/machine_defaults.py
  python/ctsm/machine_utils.py
  python/ctsm/modify_fsurdat/fsurdat_modifier.py
  python/ctsm/modify_fsurdat/modify_fsurdat.py
  python/ctsm/os_utils.py
  python/ctsm/path_utils.py
  python/ctsm/run_ctsm_py_tests.py
  python/ctsm/run_sys_tests.py
  python/ctsm/site_and_regional/regional_case.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/subset_data.py
  python/ctsm/test/joblauncher/test_unit_job_launcher_no_batch.py
  python/ctsm/test/test_sys_fsurdat_modifier.py
  python/ctsm/test/test_sys_lilac_build_ctsm.py
  python/ctsm/test/test_unit_args_utils.py
  python/ctsm/test/test_unit_lilac_build_ctsm.py
  python/ctsm/test/test_unit_lilac_make_runtime_inputs.py
  python/ctsm/test/test_unit_machine.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/test/test_unit_path_utils.py
  python/ctsm/test/test_unit_run_sys_tests.py
  python/ctsm/test/test_unit_singlept_data.py
  python/ctsm/test/test_unit_singlept_data_surfdata.py
  python/ctsm/test/test_unit_utils.py
  python/ctsm/toolchain/ctsm_case.py
  python/ctsm/unit_testing.py
  python/ctsm/utils.py
  python/six.py
  python/six_additions.py
Labels: type: code cleanup

#1570 Fix issue #1569 (History output for DISPLA is incorrect when vegetation is buried by snow)
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/main/clm_driver.F90
Labels: tag: simple bfb, PR status: ready

#1796 Add consistency checks for mesh_nx mesh_ny relative to mesh_file in gen_mksurfdata_namelist.py
  python/ctsm/mksurfdata_download_input_data.py
  tools/mksurfdata_esmf/gen_mksurfdata_jobscript_single.py
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.py
Labels: PR status: ready

#1799 Docs: Corrections to spinup instructions
  doc/source/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.rst
Labels: type: documentation

#1714 Reduce redundancy; make interfaces more similar between tools; focusing here on fsurdat_modifier and subset_data
  .git-blame-ignore-revs
  README
  doc/ChangeLog
  doc/ChangeSum
  py_env_create
  python/README.md
  python/conda_env_ctsm_py.txt
  python/conda_env_ctsm_py_cgd.txt
  python/ctsm/modify_fsurdat/fsurdat_modifier.py
  python/ctsm/modify_fsurdat/modify_fsurdat.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/test/test_sys_fsurdat_modifier.py
  test/tools/test_driver.sh
  tools/README
  tools/contrib/README
  tools/contrib/ssp_anomaly_forcing_smooth
  tools/modify_fsurdat/README
  tools/modify_fsurdat/fsurdat_modifier
  tools/modify_fsurdat/modify_template.cfg
  tools/site_and_regional/README
Labels: PR status: ready
