Repository ESCOMP/CTSM, pull requests merged in 2023-08, with the labels that each got.

#1787 Adding excess ground ice to CTSM
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ExcessIceStartup_output_sp_exice/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/ExcessIceStartup_output_sp_exice/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/ExcessIceStreams/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/ExcessIceStreams/user_nl_clm
  cime_config/usermods_dirs/output_sp_exice/include_user_mods
  cime_config/usermods_dirs/output_sp_exice/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/tech_note/References/CLM50_Tech_Note_References.rst
  doc/source/tech_note/Soil_Snow_Temperatures/CLM50_Tech_Note_Soil_Snow_Temperatures.rst
  src/biogeophys/SoilHydrologyMod.F90
  src/biogeophys/SoilTemperatureMod.F90
  src/biogeophys/TemperatureType.F90
  src/biogeophys/TotalWaterAndHeatMod.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
  src/biogeophys/WaterStateBulkType.F90
  src/biogeophys/WaterStateType.F90
  src/biogeophys/WaterType.F90
  src/cpl/mct/ExcessIceStreamType.F90
  src/cpl/share_esmf/ExcessIceStreamType.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/restFileMod.F90
  src/unit_test_shr/unittestWaterTypeFactory.F90
  src/unit_test_stubs/CMakeLists.txt
  src/unit_test_stubs/share_esmf/CMakeLists.txt
  src/unit_test_stubs/share_esmf/ExcessIceStreamType.F90
  src/unit_test_stubs/utils/restUtilMod_stub.F90.in
  src/utils/restUtilMod.F90.in
Labels: type: enhancement, tag: enh - new science

#2089 Update .ChangeLog_template
  doc/.ChangeLog_template
Labels: type: documentation

#2000 FATES API Updates to facilitate refactor
  Externals.cfg
  Externals_CLM.cfg
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
  src/utils/clmfates_paraminterfaceMod.F90
Labels: type: code cleanup, FATES update requiring an API change

#1959 migrate FATES to use the normal BGC call sequence
  .git-blame-ignore-revs
  .github/workflows/black.yml
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/rxcropmaturity.py
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNAnnualUpdateMod.F90
  src/biogeochem/CNBalanceCheckMod.F90
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNFireEmissionsMod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNNDynamicsMod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/biogeochem/CNNStateUpdate3Mod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNPrecisionControlMod.F90
  src/biogeochem/CNProductsMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/biogeochem/CNVegNitrogenStateType.F90
  src/biogeochem/CNVegStateType.F90
  src/biogeochem/CNVegStructUpdateMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/EDBGCDynMod.F90
  src/biogeochem/ch4Mod.F90
  src/biogeophys/WaterDiagnosticType.F90
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/filterMod.F90
  src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemCarbonStateType.F90
  src/soilbiogeochem/SoilBiogeochemCompetitionMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeConType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompMod.F90
  src/soilbiogeochem/SoilBiogeochemLittVertTranspMod.F90
  src/soilbiogeochem/SoilBiogeochemNLeachingMod.F90
  src/soilbiogeochem/SoilBiogeochemNStateUpdate1Mod.F90
  src/soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenStateType.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenUptakeMod.F90
  src/soilbiogeochem/SoilBiogeochemPotentialMod.F90
  src/soilbiogeochem/SoilBiogeochemPrecisionControlMod.F90
  src/soilbiogeochem/SoilBiogeochemStateType.F90
  src/soilbiogeochem/SoilBiogeochemVerticalProfileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, PR status: ready, tag: enh - new science

#2106 Rename hist fields to track them down more easily
  cime_config/usermods_dirs/newton_krylov_spinup/user_nl_clm
  cime_config/usermods_dirs/output_bgc/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/soilbiogeochem/SoilBiogeochemCarbonFluxType.F90
  src/soilbiogeochem/SoilBiogeochemCarbonStateType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenStateType.F90
Labels: type: enhancement, PR status: ready

#2045 Surface roughness modifications (cont'd)
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Meier2022_surf_rough/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/Meier2022_surf_rough/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/BiogeophysPreFluxCalcsMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/HumanIndexMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/SnowHydrologyMod.F90
  src/biogeophys/SoilTemperatureMod.F90
  src/biogeophys/UrbanFluxesMod.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
  src/main/clm_driver.F90
  src/main/clm_varcon.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/initGridCellsMod.F90
  src/main/pftconMod.F90
  src/main/subgridMod.F90
Labels: tag: enh - new science

#2115 history write optimization
  Externals.cfg
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testlist_clm_nuopc.xml
  doc/ChangeSum
  doc/release-cesm2.2.ChangeLog
  src/main/histFileMod.F90
Labels: type: enhancement, priority: high

#2056 Refactor some max_patch_per_col and maxsoil_patches loops
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeophys/SoilFluxesMod.F90
  src/biogeophys/SoilTemperatureMod.F90
  src/biogeophys/SoilWaterMovementMod.F90
  src/biogeophys/SoilWaterPlantSinkMod.F90
  src/dyn_subgrid/dynGrossUnrepMod.F90
  src/dyn_subgrid/dynHarvestMod.F90
  src/main/clm_driver.F90
  src/main/clm_varpar.F90
  src/soilbiogeochem/SoilBiogeochemVerticalProfileMod.F90
Labels: type: code cleanup

#2051 Fixes for failing nag tests
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNVegNitrogenStateType.F90
  src/biogeochem/NutrientCompetitionFlexibleCNMod.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/main/clm_initializeMod.F90
  src/main/surfrdUtilsMod.F90
Labels: type: bug, tag: next
