Repository ESCOMP/CTSM, pull requests merged in 2023-12, with the labels that each got.

#2270 Update Externals.cfg to work on Derecho
  Externals.cfg
  doc/ChangeLog
  doc/ChangeSum
Labels: type: enhancement

#2075 Add `xesmf` to the standard python environment
  python/conda_env_ctsm_py.txt
  python/conda_env_ctsm_py_latest.txt
Labels: tag: support tools only

#2080 Improvements to processing of crop calendar files
  .git-blame-ignore-revs
  python/ctsm/crop_calendars/__init__.py
  python/ctsm/crop_calendars/process_ggcmi_shdates.py
  python/ctsm/crop_calendars/regrid_ggcmi_shdates.py
  python/ctsm/test/test_sys_regrid_ggcmi_shdates.py
  python/ctsm/test/test_unit_regrid_ggcmi_shdates.py
  python/ctsm/test/testinputs/cropcals/swh_rf_ggcmi_crop_calendar_phase3_v1.01.nc4
  python/ctsm/utils.py
Labels: tag: support tools only

#2239 Add comment in LakeHydrology() pointing to issue #2227
  src/biogeophys/LakeHydrologyMod.F90
Labels: tag: simple bfb

#2271 Remove endrun for Meier2022 case to work
  src/biogeophys/BiogeophysPreFluxCalcsMod.F90
Labels: tag: bug - critical, priority: high, tag: simple bfb, tag: next

#2076 Add FATES land use change module to pass LUH2 data to FATES
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdLUH2/user_nl_clm
  cime_config/usermods_dirs/fates_sp/user_nl_clm
  doc/.ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNBalanceCheckMod.F90
  src/dyn_subgrid/dynFATESLandUseChangeMod.F90
  src/dyn_subgrid/dynSubgridDriverMod.F90
  src/main/clm_initializeMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/main/surfrdMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, FATES update requiring an API change, tag: enh - new science
