Repository ESCOMP/CTSM, pull requests merged in 2023-10, with the labels that each got.

#2134 Update to documentation for Meier et al. (2022) roughness length parameterization
  doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
  doc/source/tech_note/Lake/CLM50_Tech_Note_Lake.rst
  doc/source/tech_note/References/CLM50_Tech_Note_References.rst
Labels: type: documentation

#1991 remove deprecated shr_mpi from this module
  src/cpl/nuopc/lnd_import_export.F90
Labels: tag: simple bfb, PR status: ready

#1861 SNICAR snow albedo scheme updates
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/DryDepVelocity.F90
  src/biogeophys/AerosolMod.F90
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/SnowSnicarMod.F90
  src/biogeophys/SolarAbsorbedType.F90
  src/biogeophys/SurfaceAlbedoMod.F90
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/SurfaceRadiationMod.F90
  src/biogeophys/UrbanAlbedoMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
Labels: type: enhancement, tag: enh - new science

#2203 Turn on roughness and excess ice for the CESM3_dev branch
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/SystemTests/mksurfdataesmf.py
  cime_config/config_component.xml
  cime_config/config_pes.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeNoMeier/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeNoMeier/user_nl_clm
  python/ctsm/machine_defaults.py
  python/ctsm/machine_utils.py
Labels: type: enhancement, tag: enh - new science

#2077 Add FATES cross-grid seed dispersal mechanism
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/README
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/main/clm_driver.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, FATES update requiring an API change, tag: enh - new science
