Repository ESCOMP/CTSM, pull requests merged in 2023-11, with the labels that each got.

#2074 New outputs: N to food and seed
  cime_config/testdefs/testmods_dirs/clm/crop/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_fates.rst
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_nofates.rst
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
Labels: type: enhancement, PR status: ready, tag: enh - new science

#2161 Add excess ice user guide documentation
  doc/source/users_guide/running-special-cases/Running-with-excess-ground-ice.rst
  doc/source/users_guide/running-special-cases/index.rst
Labels: type: documentation, PR status: ready

#2220 Resolve documentation problems identified in issues #2136, #872, #993, and #2194
  doc/source/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.rst
  doc/source/tech_note/Dust/CLM50_Tech_Note_Dust.rst
  doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
  doc/source/tech_note/Hydrology/CLM50_Tech_Note_Hydrology.rst
  doc/source/tech_note/Lake/CLM50_Tech_Note_Lake.rst
  doc/source/tech_note/Land-Only_Mode/CLM50_Tech_Note_Land-Only_Mode.rst
  doc/source/tech_note/Photosynthetic_Capacity/CLM50_Tech_Note_Photosynthetic_Capacity.rst
  doc/source/tech_note/Snow_Hydrology/CLM50_Tech_Note_Snow_Hydrology.rst
  doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst
Labels: type: documentation, PR status: ready

#2221 Improvements and updates to crop documentation
  doc/source/tech_note/CN_Allocation/CLM50_Tech_Note_CN_Allocation.rst
  doc/source/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.rst
  doc/source/tech_note/Photosynthetic_Capacity/CLM50_Tech_Note_Photosynthetic_Capacity.rst
  doc/source/tech_note/Plant_Respiration/CLM50_Tech_Note_Plant_Respiration.rst
  doc/source/users_guide/running-special-cases/index.rst
  doc/source/users_guide/running-special-cases/running-with-custom-crop-calendars.rst
Labels: type: documentation, PR status: ready

#2225 Fix placeholder links in User's Guide
  doc/source/tech_note/Decomposition/CLM50_Tech_Note_Decomposition.rst
  doc/source/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.rst
  doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst
  doc/source/users_guide/adding-new-resolutions/Adding-New-Resolutions-or-New-Files-to-the-build-namelist-Database.rst
  doc/source/users_guide/adding-new-resolutions/Adding-Resolution-Names.rst
  doc/source/users_guide/adding-new-resolutions/Adding-or-Changing-Default-Filenames.rst
  doc/source/users_guide/adding-new-resolutions/index.rst
  doc/source/users_guide/overview/getting-help.rst
  doc/source/users_guide/overview/index.rst
  doc/source/users_guide/overview/introduction.rst
  doc/source/users_guide/overview/quickstart.rst
  doc/source/users_guide/overview/scientific_validation.rst
  doc/source/users_guide/running-PTCLM/adding-ptclm-site-data.rst
  doc/source/users_guide/running-PTCLM/index.rst
  doc/source/users_guide/running-PTCLM/introduction-to-ptclm.rst
  doc/source/users_guide/running-PTCLM/ptclm-examples.rst
  doc/source/users_guide/running-PTCLM/using-ptclm.rst
  doc/source/users_guide/running-single-points/index.rst
  doc/source/users_guide/running-single-points/running-pts_mode-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-configurations.rst
  doc/source/users_guide/running-single-points/single-point-and-regional-grid-configurations.rst
  doc/source/users_guide/running-special-cases/Running-stand-alone-CLM-with-transient-historical-CO2-concentration.rst
  doc/source/users_guide/running-special-cases/Running-with-MOAR-data-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
  doc/source/users_guide/running-special-cases/Running-with-your-own-previous-simulation-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/running-special-cases/Spinning-up-the-Satellite-Phenology-Model-CLMSP-spinup.rst
  doc/source/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.rst
  doc/source/users_guide/running-special-cases/index.rst
  doc/source/users_guide/running-special-cases/running-the-prognostic-crop-model.rst
  doc/source/users_guide/running-special-cases/running-with-irrigation.rst
  doc/source/users_guide/running-special-cases/what-is-a-special-case.rst
  doc/source/users_guide/setting-up-and-running-a-case/choosing-a-compset.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-datm-namelist.rst
  doc/source/users_guide/setting-up-and-running-a-case/index.rst
  doc/source/users_guide/testing/index.rst
  doc/source/users_guide/testing/testing.rst
  doc/source/users_guide/trouble-shooting/index.rst
  doc/source/users_guide/trouble-shooting/trouble-shooting.rst
  doc/source/users_guide/using-clm-tools/cprnc.rst
  doc/source/users_guide/using-clm-tools/creating-domain-files.rst
  doc/source/users_guide/using-clm-tools/creating-input-for-surface-dataset-generation.rst
  doc/source/users_guide/using-clm-tools/creating-surface-datasets.rst
  doc/source/users_guide/using-clm-tools/datasts-for-observational-sites.rst
  doc/source/users_guide/using-clm-tools/index.rst
  doc/source/users_guide/using-clm-tools/observational-sites-datasets.rst
  doc/source/users_guide/using-clm-tools/what-are-the-clm-tools.rst
Labels: type: documentation, PR status: ready

#2226 User's Guide, testing: Fix/fill Build-namelist section
  doc/source/users_guide/testing/testing.rst
Labels: type: documentation

#2230 Various documentation updates
  doc/source/tech_note/CN_Allocation/CLM50_Tech_Note_CN_Allocation.rst
  doc/source/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.rst
  doc/source/tech_note/Decomposition/CLM50_Tech_Note_Decomposition.rst
  doc/source/tech_note/Dust/CLM50_Tech_Note_Dust.rst
  doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
  doc/source/tech_note/Hydrology/CLM50_Tech_Note_Hydrology.rst
  doc/source/tech_note/Lake/CLM50_Tech_Note_Lake.rst
  doc/source/tech_note/Land-Only_Mode/CLM50_Tech_Note_Land-Only_Mode.rst
  doc/source/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.rst
  doc/source/tech_note/Photosynthetic_Capacity/CLM50_Tech_Note_Photosynthetic_Capacity.rst
  doc/source/tech_note/Plant_Respiration/CLM50_Tech_Note_Plant_Respiration.rst
  doc/source/tech_note/Snow_Hydrology/CLM50_Tech_Note_Snow_Hydrology.rst
  doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst
  doc/source/users_guide/adding-new-resolutions/Adding-New-Resolutions-or-New-Files-to-the-build-namelist-Database.rst
  doc/source/users_guide/adding-new-resolutions/Adding-Resolution-Names.rst
  doc/source/users_guide/adding-new-resolutions/Adding-or-Changing-Default-Filenames.rst
  doc/source/users_guide/adding-new-resolutions/index.rst
  doc/source/users_guide/overview/getting-help.rst
  doc/source/users_guide/overview/index.rst
  doc/source/users_guide/overview/introduction.rst
  doc/source/users_guide/overview/quickstart.rst
  doc/source/users_guide/overview/scientific_validation.rst
  doc/source/users_guide/running-PTCLM/adding-ptclm-site-data.rst
  doc/source/users_guide/running-PTCLM/index.rst
  doc/source/users_guide/running-PTCLM/introduction-to-ptclm.rst
  doc/source/users_guide/running-PTCLM/ptclm-examples.rst
  doc/source/users_guide/running-PTCLM/using-ptclm.rst
  doc/source/users_guide/running-single-points/index.rst
  doc/source/users_guide/running-single-points/running-pts_mode-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-configurations.rst
  doc/source/users_guide/running-single-points/single-point-and-regional-grid-configurations.rst
  doc/source/users_guide/running-special-cases/Running-stand-alone-CLM-with-transient-historical-CO2-concentration.rst
  doc/source/users_guide/running-special-cases/Running-with-MOAR-data-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
  doc/source/users_guide/running-special-cases/Running-with-excess-ground-ice.rst
  doc/source/users_guide/running-special-cases/Running-with-your-own-previous-simulation-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/running-special-cases/Spinning-up-the-Satellite-Phenology-Model-CLMSP-spinup.rst
  doc/source/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.rst
  doc/source/users_guide/running-special-cases/index.rst
  doc/source/users_guide/running-special-cases/running-the-prognostic-crop-model.rst
  doc/source/users_guide/running-special-cases/running-with-custom-crop-calendars.rst
  doc/source/users_guide/running-special-cases/running-with-irrigation.rst
  doc/source/users_guide/running-special-cases/what-is-a-special-case.rst
  doc/source/users_guide/setting-up-and-running-a-case/choosing-a-compset.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-datm-namelist.rst
  doc/source/users_guide/setting-up-and-running-a-case/index.rst
  doc/source/users_guide/testing/index.rst
  doc/source/users_guide/testing/testing.rst
  doc/source/users_guide/trouble-shooting/index.rst
  doc/source/users_guide/trouble-shooting/trouble-shooting.rst
  doc/source/users_guide/using-clm-tools/cprnc.rst
  doc/source/users_guide/using-clm-tools/creating-domain-files.rst
  doc/source/users_guide/using-clm-tools/creating-input-for-surface-dataset-generation.rst
  doc/source/users_guide/using-clm-tools/creating-surface-datasets.rst
  doc/source/users_guide/using-clm-tools/datasts-for-observational-sites.rst
  doc/source/users_guide/using-clm-tools/index.rst
  doc/source/users_guide/using-clm-tools/observational-sites-datasets.rst
  doc/source/users_guide/using-clm-tools/what-are-the-clm-tools.rst
Labels: type: documentation

#2154 Rearrange calculation of leaf/livestem C and N to biofuels/litter
  src/biogeochem/CNPhenologyMod.F90
Labels: type: code cleanup, PR status: ready, tag: blocker

#2157 Soil gas diffusivity bugfix
  doc/source/tech_note/Methane/CLM50_Tech_Note_Methane.rst
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_nofates.rst
  src/soilbiogeochem/SoilBiogeochemNitrifDenitrifMod.F90
  src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
Labels: type: bug, PR status: ready, tag: bug - impacts science

#2231 Fates npp fix
  Externals_CLM.cfg
  doc/ChangeLog
  doc/ChangeSum
  src/utils/clmfates_interfaceMod.F90
Labels: FATES update requiring an API change

#2199 FATES restart fix for long runs
  Externals_CLM.cfg
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/utils/clmfates_interfaceMod.F90
Labels: FATES update requiring an API change

#2164 Distinguish between ocean and wetland in fsurdat files
  .git-blame-ignore-revs
  cime_config/SystemTests/mksurfdataesmf.py
  python/ctsm/modify_input_files/fsurdat_modifier.py
  python/ctsm/modify_input_files/modify_fsurdat.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/test/test_sys_fsurdat_modifier.py
  python/ctsm/test/test_sys_mesh_modifier.py
  python/ctsm/test/test_unit_fsurdat_modifier.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/test/test_unit_singlept_data_surfdata.py
  python/ctsm/test/test_unit_subset_data.py
  python/ctsm/test/testinputs/default_data.cfg
  python/ctsm/test/testinputs/modify_fsurdat_1x1mexicocity.cfg
  python/ctsm/test/testinputs/modify_fsurdat_opt_sections.cfg
  python/ctsm/test/testinputs/modify_fsurdat_short.cfg
  python/ctsm/test/testinputs/surfdata_1x1_mexicocityMEX_hist_16pfts_CMIP6_2000_c231103.nc
  python/ctsm/test/testinputs/surfdata_1x1_mexicocityMEX_hist_16pfts_CMIP6_2000_c231103_modified.nc
  python/ctsm/test/testinputs/surfdata_5x5_amazon_hist_16pfts_CMIP6_2000_c231031.nc
  python/ctsm/test/testinputs/surfdata_5x5_amazon_hist_16pfts_CMIP6_2000_c231031_modified.nc
  python/ctsm/test/testinputs/surfdata_5x5_amazon_hist_16pfts_CMIP6_2000_c231031_modified_with_crop.nc
  src/biogeophys/EnergyFluxType.F90
  src/main/landunit_varcon.F90
  src/main/surfrdMod.F90
  src/main/surfrdUtilsMod.F90
  tools/contrib/modify_singlept_site
  tools/mksurfdata_esmf/README
  tools/mksurfdata_esmf/src/mkfileMod.F90
  tools/mksurfdata_esmf/src/mksurfdata.F90
  tools/modify_input_files/modify_fsurdat_template.cfg
  tools/site_and_regional/default_data.cfg
Labels: type: enhancement

#2044 More confined regular expression for NEON
  bld/CLMBuildNamelist.pm
  bld/env_run.xml
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/use_cases/2018-PD_transient.xml
  bld/namelist_files/use_cases/2018_control.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/buildnml
  cime_config/usermods_dirs/NEON/defaults/shell_commands
Labels: type: enhancement, priority: high

#2233 cropcalStreamMod compiler error bug fix
  src/cpl/share_esmf/cropcalStreamMod.F90
Labels: tag: simple bfb, PR status: ready

#2235 refactor ssp_anomaly_forcing
  tools/contrib/ssp_anomaly_forcing_smooth
Labels: tag: simple bfb, PR tag: no testing required, tag: support tools only

#2237 Add sowing window fields and per-harvest grainC_to_seed to restart
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CropType.F90
Labels: tag: simple bfb, type: bug

#2198 Call the new FATES-side FatesReadParameters (removing FATES->CTSM call)
  Externals_CLM.cfg
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/usermods_dirs/NEON/FATES/defaults/shell_commands
  cime_config/usermods_dirs/NEON/defaults/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  src/utils/clmfates_interfaceMod.F90
  src/utils/clmfates_paraminterfaceMod.F90
Labels: type: enhancement, type: code cleanup

#2258 New params file with changes for Meier roughness, MIMICS, and SNICAR, and changes to leafcn and k*_nonmyc
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Meier2022_surf_rough/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/Meier2022_surf_rough/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/AerosolMod.F90
  src/biogeophys/BareGroundFluxesMod.F90
  src/biogeophys/BiogeophysPreFluxCalcsMod.F90
  src/biogeophys/CanopyFluxesMod.F90
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/SnowHydrologyMod.F90
  src/biogeophys/SnowSnicarMod.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
Labels: priority: high, PR status: work in progress, tag: bug - impacts science, tag: next

#2240 Use baset_latvary parameters
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CropType.F90
  src/biogeochem/test/CMakeLists.txt
  src/biogeochem/test/Latbaset_test/CMakeLists.txt
  src/biogeochem/test/Latbaset_test/test_Latbaset.pf
Labels: tag: simple bfb
