Repository ESCOMP/CTSM, pull requests merged in 2024-04, with the labels that each got.

#2449 change needed for the addition of a dglc component in cdeps
  Externals.cfg
  cime_config/buildnml
Labels: type: enhancement, tag: simple bfb, PR status: work in progress, tag: enh - new science

#2417 Addition of clm6_0 physics option
  .git-blame-ignore-revs
  .gitignore
  bld/CLMBuildNamelist.pm
  bld/README
  bld/config_files/clm_phys_vers.pm
  bld/config_files/config_definition_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm_tools.xml
  bld/namelist_files/namelist_defaults_drydep.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/mksurfdataesmf.py
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeCiso/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode_1979Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode_2013Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeCiso/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeCiso/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_1979Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_1979Start/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_2013Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_2013Start/shell_commands
  doc/.ChangeLog_template
  doc/ChangeLog
  doc/ChangeSum
  doc/UpdateChangelog.pl
  lilac/bld_templates/ctsm_template.cfg
  python/ctsm/lilac_make_runtime_inputs.py
  python/ctsm/site_and_regional/run_neon.py
  python/ctsm/toolchain/ctsm_case.py
  tools/README
  tools/mkprocdata_map/README
  tools/mksurfdata_esmf/Makefile
  tools/mksurfdata_esmf/README
  tools/mksurfdata_esmf/README.md
  tools/mksurfdata_esmf/default_data_1850.cfg
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml
Labels: type: enhancement

#2472 B4b neon
  cime_config/usermods_dirs/NEON/defaults/shell_commands
  cime_config/usermods_dirs/NEON/defaults/user_nl_clm
  python/ctsm/site_and_regional/tower_site.py
Labels: tag: simple bfb

#2475 fix units for vector hh output
  src/main/histFileMod.F90
Labels: tag: simple bfb

#2477 One-line fix for izumi NEON-MOAB test error introduced in #2472
  cime_config/usermods_dirs/NEON/defaults/user_nl_clm
Labels: tag: simple bfb

#2464 Update ctsm5.2 branch to ctsm5.1.dev176 and some small updates
  .gitignore
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition.xsl
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/mksurfdataesmf.py
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/lilac/specific-atm-models/wrf-tools.rst
  doc/source/tech_note/Transient_Landcover/CLM50_Tech_Note_Transient_Landcover.rst
  doc/source/tech_note/Urban/CLM50_Tech_Note_Urban.rst
  doc/source/users_guide/running-PTCLM/adding-ptclm-site-data.rst
  doc/source/users_guide/running-single-points/running-single-point-configurations.rst
  doc/source/users_guide/running-special-cases/Running-with-irrigation.rst
  doc/source/users_guide/using-clm-tools/building-the-clm-tools.rst
  doc/source/users_guide/using-clm-tools/creating-input-for-surface-dataset-generation.rst
  doc/source/users_guide/using-clm-tools/creating-surface-datasets.rst
  doc/source/users_guide/using-clm-tools/observational-sites-datasets.rst
  doc/source/users_guide/using-clm-tools/what-are-the-clm-tools.rst
  python/ctsm/test/test_unit_gen_mksurfdata_jobscript_single.py
  python/ctsm/toolchain/gen_mksurfdata_jobscript_multi.py
  python/ctsm/toolchain/gen_mksurfdata_jobscript_single.py
  src/biogeochem/DUSTMod.F90
  src/cpl/share_esmf/ZenderSoilErodStreamType.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  tools/README
  tools/README.filecopies
  tools/mkprocdata_map/src/Makefile
  tools/mksurfdata_esmf/README.md
  tools/mksurfdata_esmf/gen_mksurfdata_build
Labels: type: enhancement, type: code cleanup, type: documentation

#2495 CTSM5.2 2000 fsurdat T42 64x128 file
  bld/namelist_files/namelist_defaults_ctsm.xml
Labels: type: enhancement, tag: simple bfb, type: tests, PR status: work in progress, tag: support tools only, priority: Immediate
