Repository ESCOMP/CTSM, pull requests merged in 2024-06, with the labels that each got.

#2585 Allow "manual" resets of all accumulator types
  src/biogeochem/CNDVType.F90
  src/biogeochem/CropType.F90
  src/biogeophys/EnergyFluxType.F90
  src/biogeophys/TemperatureType.F90
  src/main/accumulMod.F90
  src/main/test/accumul_test/test_accumul.pf
Labels: type: enhancement

#2599 Fix RXCROPMATURITY test
  .git-blame-ignore-revs
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/SystemTests/rxcropmaturityskipgen.py
  cime_config/config_tests.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  python/ctsm/crop_calendars/check_constant_vars.py
  python/ctsm/crop_calendars/check_rx_obeyed.py
  python/ctsm/crop_calendars/check_rxboth_run.py
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/interpolate_gdds.py
Labels: type: tests

#2552 Dust emissions moved to Object Oriented (OO) design to enable bringing in the new Dust scheme
  src/biogeochem/CMakeLists.txt
  src/biogeochem/CNVegStateType.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/DustEmisBase.F90
  src/biogeochem/DustEmisFactory.F90
  src/biogeochem/DustEmisZender2003.F90
  src/biogeochem/test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/test_DustEmisZender2003.pf
  src/biogeophys/CMakeLists.txt
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/biogeophys/test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/test_dust_soil_clay_functions.pf
  src/main/clm_driver.F90
  src/main/clm_instMod.F90
  src/main/lnd2atmMod.F90
  src/unit_test_shr/CMakeLists.txt
  src/unit_test_shr/unittestDustEmisInputs.F90
  src/unit_test_stubs/share_esmf/CMakeLists.txt
  src/unit_test_stubs/share_esmf/ZenderSoilErodStreamType.F90
Labels: type: enhancement, priority: high, type: code cleanup, tag: bfb

#2604 Merge b4bdev 20240620
  .git-blame-ignore-revs
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/SystemTests/rxcropmaturityskipgen.py
  cime_config/config_tests.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/crop_calendars/check_constant_vars.py
  python/ctsm/crop_calendars/check_rx_obeyed.py
  python/ctsm/crop_calendars/check_rxboth_run.py
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/interpolate_gdds.py
  src/biogeochem/CMakeLists.txt
  src/biogeochem/CNVegStateType.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/DustEmisBase.F90
  src/biogeochem/DustEmisFactory.F90
  src/biogeochem/DustEmisZender2003.F90
  src/biogeochem/test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/test_DustEmisZender2003.pf
  src/biogeophys/CMakeLists.txt
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/biogeophys/test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/test_dust_soil_clay_functions.pf
  src/main/clm_driver.F90
  src/main/clm_instMod.F90
  src/main/lnd2atmMod.F90
  src/unit_test_shr/CMakeLists.txt
  src/unit_test_shr/unittestDustEmisInputs.F90
  src/unit_test_stubs/share_esmf/CMakeLists.txt
  src/unit_test_stubs/share_esmf/ZenderSoilErodStreamType.F90
Labels: tag: simple bfb

#2577 Update gitfleximod to latest that fixes some particular problems.
  .gitignore
  .gitmodules
  .lib/git-fleximod/git_fleximod/cli.py
  .lib/git-fleximod/git_fleximod/git_fleximod.py
  .lib/git-fleximod/git_fleximod/gitmodules.py
  .lib/git-fleximod/git_fleximod/utils.py
  .lib/git-fleximod/pyproject.toml
  .lib/git-fleximod/tbump.toml
  .lib/git-fleximod/tests/conftest.py
  .lib/git-fleximod/tests/test_d_complex.py
  README
  README_GITFLEXIMOD.rst
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/usermods_dirs/PLUMBER2/defaults/user_nl_datm_streams
  doc/ChangeLog
  doc/ChangeSum
  doc/README.CHECKLIST.master_tags
  python/ctsm/run_sys_tests.py
  python/ctsm/test/test_unit_gen_mksurfdata_jobscript_single.py
  tools/mksurfdata_esmf/README.md
Labels: type: enhancement, tag: simple bfb, priority: Immediate

#2600 add hillslope_fsat_equals_zero
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  src/biogeophys/SaturatedExcessRunoffMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
Labels: type: enhancement, tag: bug - impacts science, tag: simple

#2628 Bring temporary branch to main-development
  .git-blame-ignore-revs
  .gitignore
  .gitmodules
  .lib/git-fleximod/git_fleximod/cli.py
  .lib/git-fleximod/git_fleximod/git_fleximod.py
  .lib/git-fleximod/git_fleximod/gitmodules.py
  .lib/git-fleximod/git_fleximod/utils.py
  .lib/git-fleximod/pyproject.toml
  .lib/git-fleximod/tbump.toml
  .lib/git-fleximod/tests/conftest.py
  .lib/git-fleximod/tests/test_d_complex.py
  README
  README_GITFLEXIMOD.rst
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/SystemTests/rxcropmaturityskipgen.py
  cime_config/config_tests.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/usermods_dirs/PLUMBER2/defaults/user_nl_datm_streams
  doc/ChangeLog
  doc/ChangeSum
  doc/README.CHECKLIST.master_tags
  python/ctsm/crop_calendars/check_constant_vars.py
  python/ctsm/crop_calendars/check_rx_obeyed.py
  python/ctsm/crop_calendars/check_rxboth_run.py
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/interpolate_gdds.py
  python/ctsm/run_sys_tests.py
  python/ctsm/test/test_unit_gen_mksurfdata_jobscript_single.py
  src/biogeochem/CMakeLists.txt
  src/biogeochem/CNVegStateType.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/DustEmisBase.F90
  src/biogeochem/DustEmisFactory.F90
  src/biogeochem/DustEmisZender2003.F90
  src/biogeochem/test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/CMakeLists.txt
  src/biogeochem/test/DustEmis_test/test_DustEmisZender2003.pf
  src/biogeophys/CMakeLists.txt
  src/biogeophys/CanopyStateType.F90
  src/biogeophys/FrictionVelocityMod.F90
  src/biogeophys/SaturatedExcessRunoffMod.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
  src/biogeophys/test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/CMakeLists.txt
  src/biogeophys/test/SoilStateInitTimeConst_test/test_dust_soil_clay_functions.pf
  src/main/clm_driver.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/lnd2atmMod.F90
  src/unit_test_shr/CMakeLists.txt
  src/unit_test_shr/unittestDustEmisInputs.F90
  src/unit_test_stubs/share_esmf/CMakeLists.txt
  src/unit_test_stubs/share_esmf/ZenderSoilErodStreamType.F90
  tools/mksurfdata_esmf/README.md
Labels: type: documentation

#2607 Fix py env create
  py_env_create
Labels: type: bug
