Repository ESCOMP/CTSM, pull requests merged in 2024-09, with the labels that each got.

#2703 Add a namelist warning when hillslope hydrology is used with initial interpolation.
  bld/CLMBuildNamelist.pm
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands
Labels: simple, bfb

#2765 Fix comments on urban thermal variables
  src/biogeophys/SoilTemperatureMod.F90
Labels: bfb

#2772 mesh_plotter improvements
  .git-blame-ignore-revs
  python/ctsm/mesh_plotter.py
  python/ctsm/site_and_regional/mesh_plot_type.py
  python/ctsm/test/test_advanced_sys_mesh_plotter.py
Labels: tests, support tools only, bfb, PR status: awaiting review

#2798 Fix clm-basic tests
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
Labels: bfb
