Repository ESCOMP/CTSM, pull requests merged in 2024-03, with the labels that each got.

#2355 Set initial t_soisno=272 for soils and 274K for urban road
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/TemperatureType.F90
Labels: PR status: ready, tag: bug - impacts science

#2394 Do "git lfs install" in "make fetch-images", and fix tillage instructions
  doc/Makefile
  doc/source/users_guide/running-special-cases/Running-the-prognostic-crop-model.rst
  doc/source/users_guide/running-special-cases/Running-with-custom-crop-calendars.rst
  doc/source/users_guide/running-special-cases/Running-with-irrigation.rst
  doc/source/users_guide/running-special-cases/What-is-a-special-case.rst
  doc/source/users_guide/running-special-cases/index.rst
Labels: tag: simple bfb, tag: support tools only

#2385 Update externals to what is expected to be in cesm2_3_beta17 fix some conda issues...
  Externals.cfg
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  manage_externals/manic/repository_git.py
  manage_externals/manic/repository_svn.py
  manage_externals/test/repos/README.md
  manage_externals/test/repos/simple-ext.svn/README.txt
  manage_externals/test/repos/simple-ext.svn/conf/authz
  manage_externals/test/repos/simple-ext.svn/conf/hooks-env.tmpl
  manage_externals/test/repos/simple-ext.svn/conf/passwd
  manage_externals/test/repos/simple-ext.svn/conf/svnserve.conf
  manage_externals/test/repos/simple-ext.svn/db/current
  manage_externals/test/repos/simple-ext.svn/db/format
  manage_externals/test/repos/simple-ext.svn/db/fs-type
  manage_externals/test/repos/simple-ext.svn/db/fsfs.conf
  manage_externals/test/repos/simple-ext.svn/db/min-unpacked-rev
  manage_externals/test/repos/simple-ext.svn/db/rep-cache.db
  manage_externals/test/repos/simple-ext.svn/db/rep-cache.db-journal
  manage_externals/test/repos/simple-ext.svn/db/revprops/0/0
  manage_externals/test/repos/simple-ext.svn/db/revprops/0/1
  manage_externals/test/repos/simple-ext.svn/db/revprops/0/2
  manage_externals/test/repos/simple-ext.svn/db/revprops/0/3
  manage_externals/test/repos/simple-ext.svn/db/revs/0/0
  manage_externals/test/repos/simple-ext.svn/db/revs/0/1
  manage_externals/test/repos/simple-ext.svn/db/revs/0/2
  manage_externals/test/repos/simple-ext.svn/db/revs/0/3
  manage_externals/test/repos/simple-ext.svn/db/txn-current
  manage_externals/test/repos/simple-ext.svn/db/txn-current-lock
  manage_externals/test/repos/simple-ext.svn/db/uuid
  manage_externals/test/repos/simple-ext.svn/db/write-lock
  manage_externals/test/repos/simple-ext.svn/format
  manage_externals/test/repos/simple-ext.svn/hooks/post-commit.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/post-lock.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/post-revprop-change.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/post-unlock.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/pre-commit.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/pre-lock.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/pre-revprop-change.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/pre-unlock.tmpl
  manage_externals/test/repos/simple-ext.svn/hooks/start-commit.tmpl
  manage_externals/test/repos/simple-ext.svn/locks/db-logs.lock
  manage_externals/test/repos/simple-ext.svn/locks/db.lock
  manage_externals/test/test_sys_checkout.py
  py_env_create
  python/README.md
  python/conda_env_ctsm_py.txt
  python/conda_env_ctsm_py_cgd.txt
  python/ctsm/machine_defaults.py
Labels: type: enhancement

#2396 Explain choice of 50% for residue removal
  doc/source/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.rst
  doc/source/tech_note/References/CLM50_Tech_Note_References.rst
  doc/source/tech_note/Vegetation_Phenology_Turnover/CLM50_Tech_Note_Vegetation_Phenology_Turnover.rst
Labels: tag: simple bfb, type: documentation

#2339 FATES history dimension control
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, FATES update requiring an API change

#2391 fix for cray compiler format issue
  src/biogeochem/CropType.F90
Labels: type: code cleanup, type: bug

#2348 Changes to improve vegetation health at high latitudes
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNPhenologyMod.F90
  src/biogeophys/SnowSnicarMod.F90
  src/biogeophys/Wateratm2lndType.F90
  src/main/atm2lndType.F90
  src/main/controlMod.F90
Labels: type: enhancement

#2424 Clean up "make all" for 5.2 branch
  .git-blame-ignore-revs
  python/ctsm/test/test_sys_gen_mksurfdata_jobscript_multi.py
  python/ctsm/test/test_sys_gen_mksurfdata_jobscript_single.py
  python/ctsm/test/test_sys_mesh_modifier.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/toolchain/gen_mksurfdata_jobscript_multi.py
  python/ctsm/toolchain/gen_mksurfdata_jobscript_single.py
  python/ctsm/toolchain/gen_mksurfdata_namelist.py
Labels: type: code cleanup, tag: bfb

#2374 Remove LILAC references to mct
  lilac/src/lilac_mod.F90
  src/CMakeLists.txt
  src/unit_test_stubs/csm_share/CMakeLists.txt
  src/unit_test_stubs/csm_share/mct_mod_stub.F90
  src/unit_test_stubs/csm_share/seq_comm_mct.F90
Labels: type: enhancement, type: code cleanup, tag: simple bfb

#2363 Refactoring of neon_site into `tower_site` and `neon_site`
  .git-blame-ignore-revs
  .gitignore
  cime_config/buildnml
  python/Makefile
  python/ctsm/site_and_regional/neon_site.py
  python/ctsm/site_and_regional/run_neon.py
  python/ctsm/site_and_regional/tower_site.py
Labels: type: enhancement, tag: bfb

#2358 Fix misplaced stopf in CNDriverMod.F90
  src/biogeochem/CNDriverMod.F90
Labels: tag: simple bfb, PR status: ready

#2429 Update some PE layouts on Derecho
  cime_config/config_pes.xml
Labels: type: enhancement

#2431 Merge b4bdev 20240321
  .git-blame-ignore-revs
  .gitignore
  cime_config/buildnml
  cime_config/config_pes.xml
  doc/ChangeLog
  doc/ChangeSum
  lilac/src/lilac_mod.F90
  python/Makefile
  python/ctsm/site_and_regional/neon_site.py
  python/ctsm/site_and_regional/run_neon.py
  python/ctsm/site_and_regional/tower_site.py
  src/CMakeLists.txt
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CropType.F90
  src/unit_test_stubs/csm_share/CMakeLists.txt
  src/unit_test_stubs/csm_share/mct_mod_stub.F90
  src/unit_test_stubs/csm_share/seq_comm_mct.F90
Labels: tag: bfb

#2432 Merge tag 'ctsm5.1.dev175' into b4bdev
  Externals_CLM.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNPhenologyMod.F90
  src/biogeophys/SnowSnicarMod.F90
  src/biogeophys/Wateratm2lndType.F90
  src/main/atm2lndType.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: tag: bfb

#1967 Move the dust emission source function soil erodibility for the Zender scheme from CAM to CTSM
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm45cam4LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm50cam5LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeZDustSoilErod/user_nl_clm
  src/biogeochem/DUSTMod.F90
  src/cpl/share_esmf/ZenderSoilErodStreamType.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
Labels: type: enhancement

#2447 Update ctsm5.2 branch to ctsm5.1.dev175
  .git-blame-ignore-revs
  .gitignore
  bld/unit_testers/build-namelist_test.pl
  cime_config/buildnml
  cime_config/config_pes.xml
  doc/ChangeLog
  doc/ChangeSum
  lilac/src/lilac_mod.F90
  python/Makefile
  python/ctsm/site_and_regional/neon_site.py
  python/ctsm/site_and_regional/run_neon.py
  python/ctsm/site_and_regional/tower_site.py
  src/CMakeLists.txt
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CropType.F90
  src/unit_test_stubs/csm_share/CMakeLists.txt
  src/unit_test_stubs/csm_share/mct_mod_stub.F90
  src/unit_test_stubs/csm_share/seq_comm_mct.F90
Labels: type: enhancement
