Repository ESCOMP/CTSM, pull requests merged in 2024-05, with the labels that each got.

#2505 Move plumber2 scripts to python directory (on b4b branch)
  python/ctsm/site_and_regional/plumber2_surf_wrapper.py
  python/ctsm/site_and_regional/plumber2_usermods.py
  python/ctsm/test/test_unit_plumber2_surf_wrapper.py
  tools/site_and_regional/plumber2_surf_wrapper
  tools/site_and_regional/plumber2_surf_wrapper.py
  tools/site_and_regional/plumber2_usermods
  tools/site_and_regional/plumber2_usermods.py
Labels: PR status: ready, tag: bfb

#2512 Fix long names for RH2M_R, AZSUN, and update nofates and fates history variable lists in User's Guide
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_fates.rst
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_nofates.rst
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
Labels: tag: simple bfb

#2528 Fix subset_data (cth and cbh not iterable)
  .git-blame-ignore-revs
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_fates.rst
  doc/source/users_guide/setting-up-and-running-a-case/history_fields_nofates.rst
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/test/test_unit_singlept_data_surfdata.py
  python/ctsm/test/test_unit_utils.py
  python/ctsm/utils.py
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/WaterDiagnosticBulkType.F90
Labels: type: tests, tag: next

#2490 CTSM5.2 1979 fsurdat and 1979-2026 landuse ne0np4 files
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/config_component.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/toolchain/gen_mksurfdata_jobscript_multi.py
  tools/mksurfdata_esmf/Makefile
Labels: type: enhancement, type: tests, PR status: ready, tag: support tools only, tag: bfb

#2501 Fix clm6_0 defaults
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/use_cases/1850_control.xml
  bld/namelist_files/use_cases/1850_noanthro_control.xml
  bld/namelist_files/use_cases/2000_control.xml
  bld/namelist_files/use_cases/2010_control.xml
  bld/namelist_files/use_cases/20thC_transient.xml
  bld/namelist_files/use_cases/stdurbpt_pd.xml
  bld/unit_testers/build-namelist_test.pl
  bld/unit_testers/cmp_baseline_lnd_in_files
  bld/unit_testers/compare_namelists
  cime_config/config_compsets.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/.pylintrc
  python/ctsm/toolchain/gen_mksurfdata_namelist.py
  tools/mksurfdata_esmf/gen_mksurfdata_build
Labels: type: enhancement

#2560 Allow prescribed gddmaturity to vary based on recent climate (v2)
  .git-blame-ignore-revs
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/RxCropCals/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCals/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdapt/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdapt/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm
  doc/source/users_guide/running-special-cases/Running-with-custom-crop-calendars.rst
  python/ctsm/crop_calendars/generate_gdd20_baseline.py
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CropType.F90
  src/cpl/share_esmf/cropcalStreamMod.F90
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_varctl.F90
  tools/crop_calendars/generate_gdd20_baseline
Labels: tag: enh - new science, tag: bfb
