Repository ESCOMP/CTSM, pull requests merged in 2024-08, with the labels that each got.

#2465 Fix/excess ice cold start
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/TemperatureType.F90
  src/biogeophys/WaterStateBulkType.F90
  src/biogeophys/WaterStateType.F90
  src/biogeophys/WaterType.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/unit_test_shr/unittestDustEmisInputs.F90
  src/unit_test_shr/unittestWaterTypeFactory.F90
Labels: type: enhancement, tag: enh - new science

#2588 New updates on MEGANv2.1
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/VOCEmissionMod.F90
  src/main/clm_driver.F90
Labels: enhancement, priority: high, PR status: ready, science

#2683 Remove broken assign-to-project Github workflow
  .github/workflows/assign-to-project.yml
Labels: no testing required

#2676 Rework crop_calendars suite and cropMonthOutput
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsNoAdapt/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/crop/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/midDecStart/include_user_mods
  doc/ChangeLog
  doc/ChangeSum
Labels: bug, PR status: ready

#2689 Bringing the PPE mods to master via b4b-dev
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
  src/biogeochem/CNFUNMod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/main/initVerticalMod.F90
  src/main/pftconMod.F90
Labels: priority: high, PR status: ready, bfb

#2711 [Fang summer '24 PR 2.1] More improvements to fire model
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FireLi2024CruJra/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FireLi2024CruJra/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFireBaseMod.F90
  src/biogeochem/CNFireFactoryMod.F90
  src/biogeochem/CNFireLi2014Mod.F90
  src/biogeochem/CNFireLi2016Mod.F90
  src/biogeochem/CNFireLi2021Mod.F90
  src/biogeochem/CNFireLi2024Mod.F90
  src/biogeophys/Wateratm2lndBulkType.F90
Labels: enhancement, science

#2718 Change CTSM machine default for Derecho to develop queue w/ 16 cpus
  python/ctsm/machine_defaults.py
Labels: enhancement, support tools only, simple, bfb, usability

#2724 Turn on explicit AC, Leung_2023, and excess ice by default
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_dust_emis.xml
  doc/ChangeLog
  doc/ChangeSum
Labels: priority: Immediate

#2699 Fix cam dust emiss control
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_drydep.xml
  bld/namelist_files/namelist_defaults_fire_emis.xml
  bld/namelist_files/namelist_definition_drv_flds.xml
  bld/unit_testers/Buildconf/camconf/drv_flds_in
  bld/unit_testers/build-namelist_test.pl
  bld/unit_testers/empty_user_nl_clm
  cime_config/config_component.xml
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
  parse_cime.cs.status
Labels: enhancement, PR status: ready, priority: Immediate
