Repository ESCOMP/CTSM, pull requests merged in 2024-07, with the labels that each got.

#2623 Change a NIWO test to HARV and update expected failures
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
Labels: tag: simple bfb

#2632 Handle CAM7
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeCiso/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeCiso/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_1979Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningMode_2013Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode_1979Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode_1979Start/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode_2013Start/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode_2013Start/shell_commands
  doc/ChangeLog
  doc/ChangeSum
Labels: type: enhancement, priority: Immediate

#2638 Remove use_dynroot and corresponding code and testing
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm50dynroots/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm50dynroots/user_nl_clm
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNRootDynMod.F90
  src/biogeophys/IrrigationMod.F90
  src/biogeophys/SoilStateType.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/pftconMod.F90
Labels: tag: simple bfb

#2275 Explicit air-conditioning adoption
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/UrbBuildTempOleson2015Mod.F90
  src/biogeophys/UrbanParamsType.F90
  src/cpl/share_esmf/UrbanTimeVarType.F90
Labels: type: enhancement, PR status: ready, tag: enh - new science

#2641 Merge b4bdev 20240711
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/clm50dynroots/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm50dynroots/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  py_env_create
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNRootDynMod.F90
  src/biogeophys/IrrigationMod.F90
  src/biogeophys/SoilStateType.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/pftconMod.F90
Labels: tag: simple bfb

#2457 Relax tolerance for truncating small snocan values in CanopyFluxes
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/CanopyFluxesMod.F90
Labels: type: enhancement, type: tests, PR status: ready

#2593 Optionally base GDD20 on per-gridcell windows, not per-hemisphere
  .git-blame-ignore-revs
  Externals.cfg
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/SystemTests/rxcropmaturityskipgen.py
  cime_config/config_tests.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/GddGen/README
  cime_config/testdefs/testmods_dirs/clm/GddGen/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/GddGen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/crop/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/cropMonthOutput/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/decStart/README
  cime_config/testdefs/testmods_dirs/clm/midDecStart/README
  cime_config/testdefs/testmods_dirs/clm/midDecStart/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/midDecStart/shell_commands
  cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm
  python/ctsm/crop_calendars/check_constant_vars.py
  python/ctsm/crop_calendars/check_rx_obeyed.py
  python/ctsm/crop_calendars/check_rxboth_run.py
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/cropcal_utils.py
  python/ctsm/crop_calendars/generate_gdd20_baseline.py
  python/ctsm/crop_calendars/generate_gdds.py
  python/ctsm/crop_calendars/generate_gdds_functions.py
  python/ctsm/crop_calendars/import_ds.py
  python/ctsm/crop_calendars/interpolate_gdds.py
  python/ctsm/run_sys_tests.py
  python/ctsm/site_and_regional/mesh_type.py
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CropType.F90
  src/biogeophys/TemperatureType.F90
  src/cpl/share_esmf/cropcalStreamMod.F90
  src/main/clm_driver.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  tools/contrib/tweak_latlons.py
  tools/mksurfdata_esmf/Makefile
Labels: type: enhancement

#2665 Merge new crop calendars into master
  .git-blame-ignore-revs
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/rxcropmaturity.py
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/GddGen/README
  cime_config/testdefs/testmods_dirs/clm/GddGen/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/GddGen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsAdaptGGCMI/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsNoAdapt/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/RxCropCalsNoAdapt/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/StreamGdd20Seasons/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/crop/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/cropMonthOutput/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/decStart/README
  cime_config/testdefs/testmods_dirs/clm/midDecStart/README
  cime_config/testdefs/testmods_dirs/clm/midDecStart/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/midDecStart/shell_commands
  cime_config/testdefs/testmods_dirs/clm/oldCropCals/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/sowingWindows/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/users_guide/running-special-cases/Running-with-custom-crop-calendars.rst
  python/ctsm/crop_calendars/check_rxboth_run.py
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/cropcal_utils.py
  python/ctsm/crop_calendars/generate_gdd20_baseline.py
  python/ctsm/crop_calendars/generate_gdds.py
  python/ctsm/crop_calendars/generate_gdds_functions.py
  python/ctsm/crop_calendars/import_ds.py
  python/ctsm/crop_calendars/interpolate_gdds.py
  python/ctsm/run_sys_tests.py
  python/ctsm/site_and_regional/mesh_type.py
  src/biogeochem/CNDVType.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CropType.F90
  src/biogeophys/EnergyFluxType.F90
  src/biogeophys/TemperatureType.F90
  src/cpl/share_esmf/cropcalStreamMod.F90
  src/main/accumulMod.F90
  src/main/clm_driver.F90
  src/main/clm_initializeMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/test/accumul_test/test_accumul.pf
  tools/contrib/tweak_latlons.py
  tools/crop_calendars/generate_gdd20_baseline
  tools/mksurfdata_esmf/Makefile
Labels: type: enhancement

#2545 Dust emissions control moved to cmeps
  bld/CLMBuildNamelist.pm
  bld/env_run.xml
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_dust_emis.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/namelist_files/namelist_definition_drv_flds.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/SystemTests/lilacsmoke.py
  cime_config/config_component.xml
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/lilac_make_runtime_inputs.py
  src/CMakeLists.txt
  src/biogeochem/DustEmisBase.F90
  src/biogeochem/DustEmisFactory.F90
  src/biogeochem/test/DustEmis_test/test_DustEmisZender2003.pf
  src/cpl/lilac/lnd_comp_esmf.F90
  src/cpl/nuopc/lnd_import_export.F90
  src/cpl/share_esmf/ZenderSoilErodStreamType.F90
  src/drv_test/CMakeLists.txt
  src/drv_test/shr_dust_emis_test/CMakeLists.txt
  src/drv_test/shr_dust_emis_test/test_shr_dust_emis.pf
  src/main/clm_varctl.F90
  src/main/controlMod.F90
Labels: type: enhancement, priority: high, blocked: dependency, tag: next
