Repository ESCOMP/CTSM, pull requests merged in 2024-01, with the labels that each got.

#2060 Refactor 20-year running means of crop GDD accumulation
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNPhenologyMod.F90
  src/biogeophys/TemperatureType.F90
Labels: type: bug, PR status: ready, tag: bug - impacts science

#2292 Improvements to processing of crop calendar files (v2)
  .git-blame-ignore-revs
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/crop_calendars/__init__.py
  python/ctsm/crop_calendars/process_ggcmi_shdates.py
  python/ctsm/crop_calendars/regrid_ggcmi_shdates.py
  python/ctsm/test/test_sys_mesh_modifier.py
  python/ctsm/test/test_sys_regrid_ggcmi_shdates.py
  python/ctsm/test/test_sys_run_neon.py
  python/ctsm/test/test_unit_utils_import_coord.py
  python/ctsm/test/testinputs/cropcals/swh_rf_ggcmi_crop_calendar_phase3_v1.01.nc4
  python/ctsm/utils.py
  tools/README
  tools/crop_calendars/process_ggcmi_shdates
  tools/crop_calendars/regrid_ggcmi_shdates
Labels: tag: support tools only

#2311 Add tillage and residue removal
  .git-blame-ignore-revs
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/remove_residues/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/remove_residues/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/till/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/till/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  doc/source/tech_note/Crop_Irrigation/CLM50_Tech_Note_Crop_Irrigation.rst
  doc/source/tech_note/Decomposition/CLM50_Tech_Note_Decomposition.rst
  doc/source/tech_note/References/CLM50_Tech_Note_References.rst
  doc/source/users_guide/running-special-cases/Running-with-tillage.rst
  python/ctsm/crop_calendars/regrid_ggcmi_shdates.py
  python/ctsm/ctsm_pylib_dependent_utils.py
  python/ctsm/test/test_unit_utils_import_coord.py
  python/ctsm/utils.py
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegNitrogenFluxType.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/readParamsMod.F90
  src/soilbiogeochem/CMakeLists.txt
  src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
  src/soilbiogeochem/TillageMod.F90
  src/soilbiogeochem/test/CMakeLists.txt
  src/soilbiogeochem/test/tillage_test/CMakeLists.txt
  src/soilbiogeochem/test/tillage_test/test_tillage.pf
  tools/contrib/add_tillage_to_paramsfile.py
Labels: type: enhancement, type: tests, tag: enh - new science

#2309 Fix izumi run_sys_tests
  .git-blame-ignore-revs
  python/ctsm/crop_calendars/regrid_ggcmi_shdates.py
  python/ctsm/ctsm_pylib_dependent_utils.py
  python/ctsm/test/test_unit_utils_import_coord.py
  python/ctsm/utils.py
Labels: tag: simple bfb, type: bug, tag: support tools only, tag: simple

#2265 Fates two stream API
  Externals_CLM.cfg
  cime_config/buildlib
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesColdSeedDisp/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStream/README
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStream/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStream/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStream/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStreamNoCompFixedBioGeo/README
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStreamNoCompFixedBioGeo/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStreamNoCompFixedBioGeo/shell_commands
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStreamNoCompFixedBioGeo/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/main/controlMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: type: enhancement, tag: enh - new science

#2323 Merge tag: Turn on meier2022 and bring in #2212
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/UrbBuildTempOleson2015Mod.F90
Labels: tag: bug - impacts science, tag: enh - new science

#2213 Automatically assign high priority items to project 25.
  .github/workflows/assign-to-project.yml
Labels: priority: low, tag: simple bfb

#2326 run_sys_tests: Check Python environment for FatesColdTwoStream tests
  .git-blame-ignore-revs
  python/ctsm/run_sys_tests.py
  python/ctsm/test/test_unit_run_sys_tests.py
Labels: tag: simple bfb, type: tests, PR status: ready

#2330 Add Izumi version of the aux_clm unit testing
  cime_config/testdefs/testlist_clm.xml
Labels: type: tests
