Repository ESCOMP/CTSM, pull requests merged in 2024-11, with the labels that each got.

#2855 Improve CLMBuildNamelist ability to detect NEON runs
  bld/CLMBuildNamelist.pm
Labels: bfb

#2852 Remove/replace refs to DATM_C*_YR_* variables
  cime_config/buildnml
  doc/source/users_guide/running-special-cases/Running-with-MOAR-data-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
  doc/source/users_guide/running-special-cases/Running-with-your-own-previous-simulation-as-atmospheric-forcing-to-spinup-the-model.rst
  doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
  src/main/clm_varctl.F90
  tools/contrib/run_clm_historical
  tools/contrib/run_clmtowers
Labels: documentation, bfb

#2840 Fix single-point matrixCN fails
  cime_config/testdefs/ExpectedTestFails.xml
  src/utils/SparseMatrixMultiplyMod.F90
Labels: bug, PR status: ready, bfb, PR status: awaiting review, size: small

#2860 Remove num_solar and implement coszen filters in UrbanAlbedoMod.F90
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/UrbanAlbedoMod.F90
Labels: bug, bfb

#2870 Fix handling of finidat with cold starts
  bld/CLMBuildNamelist.pm
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
Labels: enhancement, priority: Immediate, science, usability, size: small

#2875 run_sys_tests: Print test list in --verbose/--debug
  python/ctsm/crop_calendars/cropcal_figs_module.py
  python/ctsm/crop_calendars/generate_gdds_functions.py
  python/ctsm/run_sys_tests.py
Labels: enhancement, next, bfb, test: python

#2893 Merge b4bdev 20241125
  .lib/git-fleximod/.github/workflows/pytest.yaml
  .lib/git-fleximod/CODE_OF_CONDUCT.md
  .lib/git-fleximod/git_fleximod/cli.py
  .lib/git-fleximod/git_fleximod/git_fleximod.py
  .lib/git-fleximod/git_fleximod/gitinterface.py
  .lib/git-fleximod/git_fleximod/gitmodules.py
  .lib/git-fleximod/git_fleximod/submodule.py
  .lib/git-fleximod/git_fleximod/utils.py
  .lib/git-fleximod/poetry.lock
  .lib/git-fleximod/pyproject.toml
  .lib/git-fleximod/tbump.toml
  .lib/git-fleximod/tests/conftest.py
  .lib/git-fleximod/tests/test_e_complex_update.py
  doc/ChangeLog
  doc/ChangeSum
  doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
  python/ctsm/crop_calendars/cropcal_figs_module.py
  python/ctsm/crop_calendars/generate_gdds_functions.py
  python/ctsm/run_sys_tests.py
  src/biogeophys/SurfaceAlbedoType.F90
  src/biogeophys/UrbanAlbedoMod.F90
Labels: enhancement, code health, testing, bfb, priority: Immediate, usability
