Repository ESCOMP/CTSM, pull requests merged in 2024-10, with the labels that each got.

#2799 Change testlist_clm ne30pg3_t061 tests to ne30pg3_t232
  cime_config/testdefs/testlist_clm.xml
Labels: bfb

#2804 Remove unused variable elevclass_o in mkglcmecMod.F90
  tools/mksurfdata_esmf/src/mkglcmecMod.F90
Labels: PR status: ready, support tools only, bfb

#2678 Add check in build-namelist_test.pl
  bld/unit_testers/build-namelist_test.pl
Labels: support, tests, simple, bfb

#2434 Move hillslope variables off surface dataset
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Hillslope/shell_commands
  cime_config/testdefs/testmods_dirs/clm/Hillslope/user_nl_clm
  src/biogeophys/HillslopeHydrologyMod.F90
  src/main/clm_initializeMod.F90
  src/main/clm_instMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/histFileMod.F90
  src/main/restFileMod.F90
  src/main/surfrdMod.F90
Labels: enhancement, code health, PR status: needs testing

#2627 move from depricated shr_file to shr_log
  src/cpl/nuopc/lnd_comp_nuopc.F90
Labels: good first issue, code health, bfb, PR status: needs testing

#2806 Set eflx_building_lun to spval properly
  src/biogeophys/EnergyFluxType.F90
Labels: bfb

#2803 Tuning Leung_2023 dust emissions for clm6_0_cam7.0
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/DustEmisLeung2023.F90
  src/biogeophys/SoilStateInitTimeConstMod.F90
Labels: enhancement, science

#2829 Merge b4b-dev (2024-10-10)
  bld/unit_testers/build-namelist_test.pl
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/EnergyFluxType.F90
  src/cpl/nuopc/lnd_comp_nuopc.F90
  tools/mksurfdata_esmf/src/mkglcmecMod.F90
Labels: bfb

#2821 Clm60 finidat updates for ne30, f09, f19 grids
  bld/namelist_files/namelist_defaults_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
Labels: priority: Immediate

#2788 PPE change to sa_leaf in CanopyFluxesMod.F90
  doc/ChangeLog
  doc/ChangeSum
  src/biogeophys/CanopyFluxesMod.F90
Labels: bug, science, non-bfb

#2815 Remove include_user_mods from matrixcnOn testmod
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/matrixcnOn/include_user_mods
  doc/ChangeLog
  doc/ChangeSum
Labels: bug, testing, PR status: needs testing, test: aux_clm

#2808 Remove Clm51 references throughout or change to Clm60
  bld/CLMBuildNamelist.pm
  bld/config_files/clm_phys_vers.pm
  bld/config_files/config_definition_ctsm.xml
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_defaults_drydep.xml
  bld/namelist_files/namelist_defaults_overall.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningMode/shell_commands
  cime_config/testdefs/testmods_dirs/clm/clm51cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/clm60cam6LndTuningModeZDustSoilErod/user_nl_clm
  cime_config/usermods_dirs/NEON/FATES/README.md
  doc/.ChangeLog_template
  doc/source/users_guide/running-special-cases/Running-with-custom-crop-calendars.rst
  doc/source/users_guide/running-special-cases/Running-with-tillage.rst
  lilac/bld_templates/ctsm_template.cfg
  python/ctsm/lilac_make_runtime_inputs.py
  python/ctsm/subset_data.py
Labels: bfb

#2834 f19 + f45 16pft fsurdat/landuse files to namelist_defaults_ctsm + Makefile
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  python/ctsm/toolchain/gen_mksurfdata_jobscript_multi.py
  tools/mksurfdata_esmf/Makefile
Labels: PR status: ready, bfb, size: small

#2845 PPE parameter work -Addresses issues 2830 and 2831
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeophys/CanopyHydrologyMod.F90
  src/biogeophys/LunaMod.F90
  src/biogeophys/SnowHydrologyMod.F90
  src/main/controlMod.F90
Labels: bfb

#2716 add "polarcap" grid for cesm3 release
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
Labels: enhancement
