Repository ESCOMP/CTSM, pull requests merged in 2024-12, with the labels that each got.

#2869 Update temperature cost function for symbiotic Nfix in FUN
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  src/biogeochem/CNFUNMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/main/pftconMod.F90
Labels: enhancement, science

#2901 Bring back clm5-cam6 init_interp_attributes for ne0CONUS grid
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
Labels: testing, bfb, PR status: awaiting review

#2917 Merge b4bdev 20241220
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFUNMod.F90
  src/main/controlMod.F90
Labels: bfb
