Repository ESCOMP/CTSM, pull requests merged in 2025-08, with the labels that each got.

#3395 Merge b4bdev 20250807
  doc/ChangeLog
  doc/ChangeSum
  doc/README.CHECKLIST.master_tags
  tools/contrib/abm_raw.ncl
  tools/contrib/popden.ncl
Labels: bfb

#3398 Merge master 20250808
  doc/ChangeLog
  doc/ChangeSum
  doc/README.CHECKLIST.master_tags
Labels: bfb

#3403 Fix py_env_create and tests
  py_env_create
  python/ctsm/test/test_sys_py_env_create.py
  python/empty.yml
Labels: bfb

#3390 Make npcropmin/max private to pftconMod
  src/biogeochem/CNAllocationMod.F90
  src/biogeochem/CNC14DecayMod.F90
  src/biogeochem/CNCIsoFluxMod.F90
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNFUNMod.F90
  src/biogeochem/CNFireEmissionsMod.F90
  src/biogeochem/CNGRespMod.F90
  src/biogeochem/CNGapMortalityMod.F90
  src/biogeochem/CNMRespMod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegCarbonFluxType.F90
  src/biogeochem/CNVegCarbonStateType.F90
  src/biogeochem/CNVegMatrixMod.F90
  src/biogeochem/CNVegNitrogenStateType.F90
  src/biogeochem/CNVegStructUpdateMod.F90
  src/biogeochem/CropType.F90
  src/biogeochem/DryDepVelocity.F90
  src/biogeochem/NutrientCompetitionCLM45defaultMod.F90
  src/biogeochem/NutrientCompetitionFlexibleCNMod.F90
  src/biogeophys/PhotosynthesisMod.F90
  src/biogeophys/TemperatureType.F90
  src/cpl/share_esmf/cropcalStreamMod.F90
  src/main/filterMod.F90
  src/main/pftconMod.F90
  src/soilbiogeochem/TillageMod.F90
Labels: code health, bfb

#3418 Endrun work
  src/main/abortutils.F90
  src/main/decompMod.F90
  src/main/test/CMakeLists.txt
  src/main/test/abortutils_test/CMakeLists.txt
  src/main/test/abortutils_test/test_abortutils.pf
Labels: enhancement, code health, testing, bfb

#3408 Logging improvements for GDD-generation workflow
  .git-blame-ignore-revs
  python/ctsm/crop_calendars/cropcal_module.py
  python/ctsm/crop_calendars/generate_gdds.py
  python/ctsm/crop_calendars/generate_gdds_functions.py
  python/ctsm/crop_calendars/import_ds.py
  python/ctsm/ctsm_logging.py
  python/ctsm/test/test_unit_ctsm_logging.py
  python/ctsm/utils.py
  src/biogeochem/CNPhenologyMod.F90
Labels: enhancement, blocker, bfb, PR status: needs testing, test: python

#2992 ctsm5.3.072: Incorporating a new vertical movement scheme for soil nitrate
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/nvmovement/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/nvmovement/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNDriverMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeophys/SoilHydrologyType.F90
  src/biogeophys/SoilWaterMovementMod.F90
  src/main/clm_driver.F90
  src/main/clm_varcon.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
  src/soilbiogeochem/SoilBiogeochemNLeachingMod.F90
  src/soilbiogeochem/SoilNitrogenMovementMod.F90
Labels: enhancement, documentation, testing, science
