Repository ESCOMP/CTSM, pull requests merged in 2025-01, with the labels that each got.

#2926 Bug fix for izumi nag tests to pass (PR into b4b-dev)
  src/biogeochem/CNFUNMod.F90
Labels: bug, bfb

#2925 Bug fix for izumi nag tests to pass (PR into tmp-241219)
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNFUNMod.F90
Labels: bug, bfb

#2084 ctsm5.3.019: Stop running 0th time step
  doc/ChangeLog
  doc/ChangeSum
  python/ctsm/crop_calendars/generate_gdds_functions.py
  src/biogeochem/CNPhenologyMod.F90
  src/biogeochem/CNVegetationFacade.F90
  src/biogeochem/CropType.F90
  src/biogeochem/dynCNDVMod.F90
  src/cpl/lilac/lnd_comp_esmf.F90
  src/cpl/nuopc/lnd_comp_nuopc.F90
  src/main/clm_driver.F90
  src/main/histFileMod.F90
  src/unit_test_shr/unittestTimeManagerMod.F90
  src/utils/AnnualFluxDribbler.F90
  src/utils/clm_time_manager.F90
  src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
Labels: external, PR status: needs testing, non-bfb, test: python, test: aux_clm, test: rivers

#2022 Delete unused hist_add_subscript method (no references in the CTSM repo)
  src/main/histFileMod.F90
Labels: code health

#2789 Update "What's New in CTSM 5.3"
  WhatsNewInCTSM5.3.md
Labels: documentation, bfb

#2937 Minor test tweaks
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
Labels: testing, test: none, blocker, bfb
