Repository ESCOMP/CTSM, pull requests merged in 2025-05, with the labels that each got.

#3072 User control over snow thermal conductivity scheme over glaciers
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  src/biogeophys/LakeFluxesMod.F90
  src/biogeophys/LakeTemperatureMod.F90
  src/biogeophys/SoilTemperatureMod.F90
  src/main/clm_varctl.F90
  src/main/controlMod.F90
Labels: enhancement, investigation, bfb, science, PR status: needs testing

#3063 Fix FATES electron transport variable being set prior to passing to FATES
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/FatesColdElecTransJB/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdElecTransJB/user_nl_clm
  src/utils/clmfates_interfaceMod.F90
Labels: FATES, bfb, test: fates, done

#3122 Fix a couple of things in documentation conf.py
  doc/source/conf.py
Labels: bfb

#3100 Fix Longitude comparison error for regional subset_data
  .git-blame-ignore-revs
  .gitignore
  python/Makefile
  python/ctsm/longitude.py
  python/ctsm/site_and_regional/regional_case.py
  python/ctsm/subset_data.py
  python/ctsm/test/test_sys_subset_data.py
  python/ctsm/test/test_unit_longitude.py
  python/ctsm/test/test_unit_subset_data.py
  python/ctsm/test/test_unit_utils.py
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon/domain.lnd.5x5pt-amazon_navy_TMP_c250508.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon/domain.lnd.5x5pt-amazon_navy_TMP_c250508_ESMF_UNSTRUCTURED_MESH.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon/surfdata_TMP_amazon_hist_16pfts_CMIP6_2000_c250508.nc
  python/ctsm/test/testinputs/subset_data_amazon.cfg
  python/ctsm/utils.py
Labels: bug, test: python

#3056 QOL improvements in mksurfdata_esmf makefile
  tools/mksurfdata_esmf/Makefile
Labels: enhancement, bfb, usability, size: small, test: mksurfdata

#3128 Fix ctsm-docs container version tagging
  .github/workflows/docker-image-build-publish.yml
  .github/workflows/docker-image-build.yml
  .github/workflows/docker-image-common.yml
  .github/workflows/docker-image-get-version.yml
  doc/ctsm-docs_container/Dockerfile
  doc/ctsm-docs_container/README.md
  doc/ctsm-docs_container/get_version.sh
Labels: documentation, devops

#3138 Don't build docs for ChangeLog/Sum
  .github/workflows/docs.yml
Labels: bfb, devops

#3140 Fix error when docker-image-common.yml runs on new tag
  .github/workflows/docker-image-build.yml
  .github/workflows/docker-image-common.yml
Labels: bfb, devops

#3143 Don't run workflows on plain tag creation
  .github/workflows/docker-image-build.yml
  .github/workflows/docs-ctsm_pylib.yml
  .github/workflows/docs.yml
  .github/workflows/fleximod_test.yaml
  .github/workflows/formatting_python.yml
Labels: bug, bfb, devops

#3144 Add docs issue template
  .github/ISSUE_TEMPLATE/03_documentation.md
  .github/ISSUE_TEMPLATE/03_other.md
  .github/ISSUE_TEMPLATE/04_other.md
Labels: next, bfb, devops

#3162 Remove hardcoded paths in gen_mksurfdata_namelist.xml
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml
Labels: code health, bfb, size: small, test: python, test: mksurfdata

#2686 ctsm5.3.053: Fix and improve anomaly forcings for ISSP cases
  .github/workflows/validate_xml.py
  .github/workflows/xml-check.yml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/datm_rcp45_anom_forc/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/datm_rcp45_anom_forc/user_nl_datm
  cime_config/testdefs/testmods_dirs/clm/datm_ssp126_anom_forc/user_nl_datm
  cime_config/testdefs/testmods_dirs/clm/datm_ssp126_anom_forc/user_nl_datm_streams
  cime_config/testdefs/testmods_dirs/clm/noAnomalyForcing/user_nl_datm
  cime_config/usermods_dirs/clm/NEON/FATES/defaults/user_nl_datm
  cime_config/usermods_dirs/clm/NEON/defaults/user_nl_datm
  cime_config/usermods_dirs/clm/NEON/defaults/user_nl_datm_streams
  cime_config/usermods_dirs/clm/PLUMBER2/defaults/user_nl_datm
  cime_config/usermods_dirs/clm/PLUMBER2/defaults/user_nl_datm_streams
  doc/ChangeLog
  doc/ChangeSum
  doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
Labels: enhancement, bug, blocker, external, usability, docs:update, docs-loc:users-guide
