Repository ESCOMP/CTSM, pull requests merged in 2025-07, with the labels that each got.

#3314 Fix string replacements in lreprstruct test
  cime_config/SystemTests/lreprstruct.py
Labels: bug, bfb

#3326 b4b-dev merge 2025-07-10
  .git-blame-ignore-revs
  .github/workflows/python-tests.yml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/SystemTests/lreprstruct.py
  cime_config/SystemTests/sspmatrixcn.py
  cime_config/config_pes.xml
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/f09_FillMissingW_Urban/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/f09_FillMissingW_Urban/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/run_self_tests/shell_commands
  doc/ChangeLog
  doc/ChangeSum
  doc/source/tech_note/Snow_Hydrology/CLM50_Tech_Note_Snow_Hydrology.rst
  doc/source/users_guide/working-with-documentation/tips-for-working-with-rst.md
  python/ctsm/longitude.py
  python/ctsm/site_and_regional/regional_case.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/subset_data.py
  python/ctsm/test/test_sys_gen_mksurfdata_jobscript_single_derecho.py
  python/ctsm/test/test_sys_subset_data.py
  python/ctsm/test/test_unit_gen_mksurfdata_jobscript_single.py
  python/ctsm/test/test_unit_longitude.py
  python/ctsm/test/test_unit_singlept_data.py
  python/ctsm/test/test_unit_singlept_data_surfdata.py
  python/ctsm/test/test_unit_sspmatrix.py
  python/ctsm/test/test_unit_subset_data.py
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Prec.-69.0_-12.0.1986.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Prec.-69.0_-12.0.1987.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Prec.-69.0_-12.0.1988.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Solr.-69.0_-12.0.1986.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Solr.-69.0_-12.0.1987.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.Solr.-69.0_-12.0.1988.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.TPQWL.-69.0_-12.0.1986.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.TPQWL.-69.0_-12.0.1987.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/clmforc.CRUJRAv2.5_0.5x0.5.TPQWL.-69.0_-12.0.1988.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_datm_amazon_type180_nositename/datmdata/domain.crujra_v2.3_0.5x0.5_-69.0_-12.0_c250620.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_landuse_amazon_type360_nositename/landuse.timeseries_291.0_-12.0_amazon_hist_1850-1853_78pfts_c250618.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_landuse_amazon_type360_nositename/surfdata_291.0_-12.0_amazon_hist_1850_78pfts_c250618.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_pt_surface_amazon_type180_nositename/surfdata_-69.0_-12.0_amazon_hist_16pfts_CMIP6_2000_c250617.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon_noregname/domain.lnd.5x5pt-amazon_navy_291.0-299.0_-12.0--7.0_c250508.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon_noregname/domain.lnd.5x5pt-amazon_navy_291.0-299.0_-12.0--7.0_c250508_ESMF_UNSTRUCTURED_MESH.nc
  python/ctsm/test/testinputs/expected_result_files/test_subset_data_reg_amazon_noregname/surfdata_291.0-299.0_-12.0--7.0_amazon_hist_16pfts_CMIP6_2000_c250508.nc
  python/ctsm/test_gen_mksurfdata_jobscript_single_parent.py
  python/ctsm/unit_testing.py
  src/cpl/nuopc/lnd_comp_nuopc.F90
  src/init_interp/initInterp.F90
  src/init_interp/initInterpMindist.F90
  src/init_interp/test/initInterpMindist_test/initInterpMindistTestUtils.pf
  src/init_interp/test/initInterpMindist_test/test_set_mindist.pf
  src/main/clm_initializeMod.F90
Labels: non-bfb

#3343 Harden GitHub actions
  .github/workflows/check-clm6-aliases.yml
  .github/workflows/docker-image-build-publish.yml
  .github/workflows/docker-image-common.yml
  .github/workflows/docker-image-get-version.yml
  .github/workflows/docs-build-and-deploy.yml
  .github/workflows/docs-common.yml
  .github/workflows/docs-omnibus.yml
  .github/workflows/docs-update-ctsm_pylib.yml
  .github/workflows/docs-update-dependency-common.yml
  .github/workflows/docs-update-doc-builder.yml
  .github/workflows/docs.yml
  .github/workflows/python-tests.yml
  .github/workflows/xml-check.yml
  doc/ctsm-docs_container/Dockerfile
Labels: bfb, devops

#3233 Make ctsm54 datasets
  bld/namelist_files/namelist_defaults_ctsm.xml
  tools/mksurfdata_esmf/Makefile
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml
  tools/mksurfdata_esmf/modify_1x1_urbanc_alpha.cfg
Labels: test: mksurfdata

#3347 Urban mesh was pointing to a 3x3min instead of a 0.25x0.25 file
  tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml
Labels: bug

#2534 Adds a broadcast of the namelist value 'urbantvmapalgo'
  bld/namelist_files/namelist_definition_ctsm.xml
  bld/unit_testers/build-namelist_test.pl
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/f09_ObscureStreamOpts/README
  cime_config/testdefs/testmods_dirs/clm/f09_ObscureStreamOpts/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/f09_ObscureStreamOpts/shell_commands
  cime_config/testdefs/testmods_dirs/clm/f09_ObscureStreamOpts/user_nl_clm
  src/cpl/share_esmf/FireDataBaseType.F90
  src/cpl/share_esmf/UrbanTimeVarType.F90
  src/cpl/share_esmf/ndepStreamMod.F90
Labels: enhancement, good first issue, bug, bfb, usability, PR status: needs testing

#3365 Merge master 20250728
  bld/CLMBuildNamelist.pm
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  doc/ChangeLog
  doc/ChangeSum
  src/dyn_subgrid/dynSubgridControlMod.F90
  src/main/histFileMod.F90
Labels: bfb

#3352 Add abm and popden scripts to /tools/contrib
  tools/contrib/abm_raw.ncl
  tools/contrib/popden.ncl
Labels: test: none, bfb

#3354 this change is needed for proper operation of st_archive
  cime_config/config_archive.xml
  cime_config/testdefs/testlist_clm.xml
Labels: bug, testing, next, bfb
