Repository ESCOMP/CTSM, pull requests merged in 2025-03, with the labels that each got.

#2975 ctsm5.3.028: Move Izumi intel and gnu tests to Derecho
  cime_config/testdefs/testlist_clm.xml
  doc/ChangeLog
  doc/ChangeSum
  tools/contrib/remove_duplicate_tests.py
Labels: testing, PR status: needs testing, test: aux_clm

#2972 Make "Bytnerowicz" the default nfix_method for clm6
  bld/namelist_files/namelist_defaults_ctsm.xml
  bld/namelist_files/namelist_definition_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
Labels: non-bfb

#2955 ctsm5.3.030: Fix FATES branch runs
  cime_config/testdefs/ExpectedTestFails.xml
  cime_config/testdefs/testlist_clm.xml
  cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdDryDepSatPhen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdMeganSatPhen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/FatesColdSatPhen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/GddGen/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/fire_emis/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/glcMEC_long/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/main/clm_initializeMod.F90
  src/utils/clmfates_interfaceMod.F90
Labels: bug, PR status: ready, test: aux_clm, test: fates

#2991 Add Spectral Element grid equilibrium script to tools/contrib
  tools/contrib/README
  tools/contrib/SpinupStability_BGC_v11_SE.ncl
Labels: enhancement, test: none, bfb

#3013 Merge b4bdev 20250313
  cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStream/include_user_mods
  cime_config/testdefs/testmods_dirs/clm/FatesColdTwoStreamNoCompFixedBioGeo/include_user_mods
  doc/ChangeLog
  doc/ChangeSum
  tools/contrib/README
  tools/contrib/SpinupStability_BGC_v11_SE.ncl
Labels: bfb

#2365 MIMICS updates
  bld/namelist_files/namelist_defaults_ctsm.xml
  cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
  cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
  doc/ChangeLog
  doc/ChangeSum
  src/biogeochem/CNCStateUpdate1Mod.F90
  src/biogeochem/CNNStateUpdate1Mod.F90
  src/main/clm_varpar.F90
  src/main/pftconMod.F90
  src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
Labels: science, non-bfb

#3030 Avoid mksurfdata_esmf pitfall with --model-mesh-nx, ny
  tools/mksurfdata_esmf/src/mkinputMod.F90
Labels: bug, bfb

#3023 Get pFUnit-based unit tests working on my Mac
  src/CMakeLists.txt
Labels: bfb, devops

#3002 Update single point docs (and improve subset_data etc. erroring)
  .git-blame-ignore-revs
  doc/source/users_guide/overview/introduction.rst
  doc/source/users_guide/running-single-points/index.rst
  doc/source/users_guide/running-single-points/running-pts_mode-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-subset-data.rst
  doc/source/users_guide/running-single-points/single-point-and-regional-grid-configurations.rst
  python/ctsm/config_utils.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/subset_data.py
  python/ctsm/test/test_unit_args_utils.py
  python/ctsm/test/test_unit_config_utils.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/test/test_unit_subset_data.py
  python/ctsm/test/test_unit_utils.py
Labels: documentation, testing, bfb, test: docs

#3037 ctsm5.3.035: b4b-dev merge 2025-03-27
  .git-blame-ignore-revs
  cime_config/testdefs/ExpectedTestFails.xml
  doc/ChangeLog
  doc/ChangeSum
  doc/source/users_guide/overview/introduction.rst
  doc/source/users_guide/running-single-points/index.rst
  doc/source/users_guide/running-single-points/running-pts_mode-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-configurations.rst
  doc/source/users_guide/running-single-points/running-single-point-subset-data.rst
  doc/source/users_guide/running-single-points/single-point-and-regional-grid-configurations.rst
  python/ctsm/config_utils.py
  python/ctsm/site_and_regional/single_point_case.py
  python/ctsm/subset_data.py
  python/ctsm/test/test_unit_args_utils.py
  python/ctsm/test/test_unit_config_utils.py
  python/ctsm/test/test_unit_modify_fsurdat.py
  python/ctsm/test/test_unit_subset_data.py
  python/ctsm/test/test_unit_utils.py
  src/CMakeLists.txt
  tools/mksurfdata_esmf/src/mkinputMod.F90
Labels: bfb
